/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v6 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StorageJsonFragment } from './StorageJsonFragment';
import {
    StorageJsonFragmentFromJSON,
    StorageJsonFragmentFromJSONTyped,
    StorageJsonFragmentToJSON,
} from './StorageJsonFragment';

/**
 * 
 * @export
 * @interface AppendArrSubDocumentRequest
 */
export interface AppendArrSubDocumentRequest {
    /**
     * Fragments to be appended
     * @type {Array<StorageJsonFragment>}
     * @memberof AppendArrSubDocumentRequest
     */
    updates: Array<StorageJsonFragment>;
}

/**
 * Check if a given object implements the AppendArrSubDocumentRequest interface.
 */
export function instanceOfAppendArrSubDocumentRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "updates" in value;

    return isInstance;
}

export function AppendArrSubDocumentRequestFromJSON(json: any): AppendArrSubDocumentRequest {
    return AppendArrSubDocumentRequestFromJSONTyped(json, false);
}

export function AppendArrSubDocumentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppendArrSubDocumentRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'updates': ((json['updates'] as Array<any>).map(StorageJsonFragmentFromJSON)),
    };
}

export function AppendArrSubDocumentRequestToJSON(value?: AppendArrSubDocumentRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'updates': ((value.updates as Array<any>).map(StorageJsonFragmentToJSON)),
    };
}

