/* tslint:disable */
/* eslint-disable */
/**
 * lap-legend-race-game
 * Your custom SDK
 *
 * The version of the OpenAPI document: lap-legend-race-game: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthUpdateUsernamePasswordRequest
 */
export interface AuthUpdateUsernamePasswordRequest {
    /**
     * New password to be set
     * @type {string}
     * @memberof AuthUpdateUsernamePasswordRequest
     */
    newPassword: string;
    /**
     * Old password to be verified
     * @type {string}
     * @memberof AuthUpdateUsernamePasswordRequest
     */
    oldPassword: string;
    /**
     * User's login ID
     * @type {string}
     * @memberof AuthUpdateUsernamePasswordRequest
     */
    username: string;
}

/**
 * Check if a given object implements the AuthUpdateUsernamePasswordRequest interface.
 */
export function instanceOfAuthUpdateUsernamePasswordRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "newPassword" in value;
    isInstance = isInstance && "oldPassword" in value;
    isInstance = isInstance && "username" in value;

    return isInstance;
}

export function AuthUpdateUsernamePasswordRequestFromJSON(json: any): AuthUpdateUsernamePasswordRequest {
    return AuthUpdateUsernamePasswordRequestFromJSONTyped(json, false);
}

export function AuthUpdateUsernamePasswordRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthUpdateUsernamePasswordRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'newPassword': json['new_password'],
        'oldPassword': json['old_password'],
        'username': json['username'],
    };
}

export function AuthUpdateUsernamePasswordRequestToJSON(value?: AuthUpdateUsernamePasswordRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'new_password': value.newPassword,
        'old_password': value.oldPassword,
        'username': value.username,
    };
}

