/* tslint:disable */
/* eslint-disable */
/**
 * test
 * Your custom SDK
 *
 * The version of the OpenAPI document: test: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AuthLoginMetadata } from './AuthLoginMetadata';
import {
    AuthLoginMetadataFromJSON,
    AuthLoginMetadataFromJSONTyped,
    AuthLoginMetadataToJSON,
} from './AuthLoginMetadata';

/**
 * 
 * @export
 * @interface AuthEmailLoginRequest
 */
export interface AuthEmailLoginRequest {
    /**
     * Whether to create a user, if it does not exist
     * @type {boolean}
     * @memberof AuthEmailLoginRequest
     */
    createUser?: boolean;
    /**
     * Email address used as login
     * @type {string}
     * @memberof AuthEmailLoginRequest
     */
    email: string;
    /**
     * 
     * @type {AuthLoginMetadata}
     * @memberof AuthEmailLoginRequest
     */
    loginMetadata?: AuthLoginMetadata;
    /**
     * OTP code received by the user
     * @type {string}
     * @memberof AuthEmailLoginRequest
     */
    otp: string;
}

/**
 * Check if a given object implements the AuthEmailLoginRequest interface.
 */
export function instanceOfAuthEmailLoginRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "otp" in value;

    return isInstance;
}

export function AuthEmailLoginRequestFromJSON(json: any): AuthEmailLoginRequest {
    return AuthEmailLoginRequestFromJSONTyped(json, false);
}

export function AuthEmailLoginRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthEmailLoginRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createUser': !exists(json, 'create_user') ? undefined : json['create_user'],
        'email': json['email'],
        'loginMetadata': !exists(json, 'login_metadata') ? undefined : AuthLoginMetadataFromJSON(json['login_metadata']),
        'otp': json['otp'],
    };
}

export function AuthEmailLoginRequestToJSON(value?: AuthEmailLoginRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'create_user': value.createUser,
        'email': value.email,
        'login_metadata': AuthLoginMetadataToJSON(value.loginMetadata),
        'otp': value.otp,
    };
}

