/* tslint:disable */
/* eslint-disable */
/**
 * lap-legend-race-game
 * Your custom SDK
 *
 * The version of the OpenAPI document: lap-legend-race-game: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AuthUser } from './AuthUser';
import {
    AuthUserFromJSON,
    AuthUserFromJSONTyped,
    AuthUserToJSON,
} from './AuthUser';

/**
 * 
 * @export
 * @interface AuthEmailLoginResponse
 */
export interface AuthEmailLoginResponse {
    /**
     * 
     * @type {AuthUser}
     * @memberof AuthEmailLoginResponse
     */
    user?: AuthUser;
}

/**
 * Check if a given object implements the AuthEmailLoginResponse interface.
 */
export function instanceOfAuthEmailLoginResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AuthEmailLoginResponseFromJSON(json: any): AuthEmailLoginResponse {
    return AuthEmailLoginResponseFromJSONTyped(json, false);
}

export function AuthEmailLoginResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthEmailLoginResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': !exists(json, 'user') ? undefined : AuthUserFromJSON(json['user']),
    };
}

export function AuthEmailLoginResponseToJSON(value?: AuthEmailLoginResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': AuthUserToJSON(value.user),
    };
}

