/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v6 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AuthLoginTypeType = {
    UnspecifiedLoginType: 'UNSPECIFIED_LOGIN_TYPE',
    Email: 'EMAIL',
    Password: 'PASSWORD',
    Anon: 'ANON',
    Facebook: 'FACEBOOK',
    Google: 'GOOGLE',
    Apple: 'APPLE',
    Steam: 'STEAM',
    Xbox: 'XBOX',
    Epic: 'EPIC',
    App: 'APP',
    Discord: 'DISCORD',
    EmailPassword: 'EMAIL_PASSWORD',
    UsernamePassword: 'USERNAME_PASSWORD',
    X: 'X'
} as const;
export type AuthLoginTypeType = typeof AuthLoginTypeType[keyof typeof AuthLoginTypeType];


export function AuthLoginTypeTypeFromJSON(json: any): AuthLoginTypeType {
    return AuthLoginTypeTypeFromJSONTyped(json, false);
}

export function AuthLoginTypeTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthLoginTypeType {
    return json as AuthLoginTypeType;
}

export function AuthLoginTypeTypeToJSON(value?: AuthLoginTypeType | null): any {
    return value as any;
}

