/* tslint:disable */
/* eslint-disable */
/**
 * test
 * Your custom SDK
 *
 * The version of the OpenAPI document: test: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthRecoverEmailAccountRequest
 */
export interface AuthRecoverEmailAccountRequest {
    /**
     * Email address to recover
     * @type {string}
     * @memberof AuthRecoverEmailAccountRequest
     */
    email: string;
}

/**
 * Check if a given object implements the AuthRecoverEmailAccountRequest interface.
 */
export function instanceOfAuthRecoverEmailAccountRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;

    return isInstance;
}

export function AuthRecoverEmailAccountRequestFromJSON(json: any): AuthRecoverEmailAccountRequest {
    return AuthRecoverEmailAccountRequestFromJSONTyped(json, false);
}

export function AuthRecoverEmailAccountRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthRecoverEmailAccountRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function AuthRecoverEmailAccountRequestToJSON(value?: AuthRecoverEmailAccountRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
    };
}

