/* tslint:disable */
/* eslint-disable */
/**
 * lap-legend-race-game
 * Your custom SDK
 *
 * The version of the OpenAPI document: lap-legend-race-game: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthOtpRequest
 */
export interface AuthOtpRequest {
    /**
     * Email address to send OTP to
     * @type {string}
     * @memberof AuthOtpRequest
     */
    email: string;
    /**
     * If set to true, OTP won't be sent if user doesn't exist
     * @type {boolean}
     * @memberof AuthOtpRequest
     */
    validateUserExists?: boolean;
}

/**
 * Check if a given object implements the AuthOtpRequest interface.
 */
export function instanceOfAuthOtpRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;

    return isInstance;
}

export function AuthOtpRequestFromJSON(json: any): AuthOtpRequest {
    return AuthOtpRequestFromJSONTyped(json, false);
}

export function AuthOtpRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthOtpRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'validateUserExists': !exists(json, 'validate_user_exists') ? undefined : json['validate_user_exists'],
    };
}

export function AuthOtpRequestToJSON(value?: AuthOtpRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'validate_user_exists': value.validateUserExists,
    };
}

