/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v6 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthVerifyEmailRequest
 */
export interface AuthVerifyEmailRequest {
    /**
     * Email address to verify
     * @type {string}
     * @memberof AuthVerifyEmailRequest
     */
    email: string;
    /**
     * Verification code received by the user
     * @type {string}
     * @memberof AuthVerifyEmailRequest
     */
    verificationCode: string;
}

/**
 * Check if a given object implements the AuthVerifyEmailRequest interface.
 */
export function instanceOfAuthVerifyEmailRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "verificationCode" in value;

    return isInstance;
}

export function AuthVerifyEmailRequestFromJSON(json: any): AuthVerifyEmailRequest {
    return AuthVerifyEmailRequestFromJSONTyped(json, false);
}

export function AuthVerifyEmailRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthVerifyEmailRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'verificationCode': json['verification_code'],
    };
}

export function AuthVerifyEmailRequestToJSON(value?: AuthVerifyEmailRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'verification_code': value.verificationCode,
    };
}

