/* tslint:disable */
/* eslint-disable */
/**
 * test
 * Your custom SDK
 *
 * The version of the OpenAPI document: test: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AuthLoginMetadata } from './AuthLoginMetadata';
import {
    AuthLoginMetadataFromJSON,
    AuthLoginMetadataFromJSONTyped,
    AuthLoginMetadataToJSON,
} from './AuthLoginMetadata';

/**
 * 
 * @export
 * @interface AuthAppleLoginRequest
 */
export interface AuthAppleLoginRequest {
    /**
     * Whether to create a user, if it does not exist
     * @type {boolean}
     * @memberof AuthAppleLoginRequest
     */
    createUser?: boolean;
    /**
     * 
     * @type {AuthLoginMetadata}
     * @memberof AuthAppleLoginRequest
     */
    loginMetadata?: AuthLoginMetadata;
    /**
     * Apple token generated on the client
     * @type {string}
     * @memberof AuthAppleLoginRequest
     */
    token: string;
}

/**
 * Check if a given object implements the AuthAppleLoginRequest interface.
 */
export function instanceOfAuthAppleLoginRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "token" in value;

    return isInstance;
}

export function AuthAppleLoginRequestFromJSON(json: any): AuthAppleLoginRequest {
    return AuthAppleLoginRequestFromJSONTyped(json, false);
}

export function AuthAppleLoginRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthAppleLoginRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createUser': !exists(json, 'create_user') ? undefined : json['create_user'],
        'loginMetadata': !exists(json, 'login_metadata') ? undefined : AuthLoginMetadataFromJSON(json['login_metadata']),
        'token': json['token'],
    };
}

export function AuthAppleLoginRequestToJSON(value?: AuthAppleLoginRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'create_user': value.createUser,
        'login_metadata': AuthLoginMetadataToJSON(value.loginMetadata),
        'token': value.token,
    };
}

