/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v6 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AuthUser } from './AuthUser';
import {
    AuthUserFromJSON,
    AuthUserFromJSONTyped,
    AuthUserToJSON,
} from './AuthUser';

/**
 * 
 * @export
 * @interface AuthRefreshResponse
 */
export interface AuthRefreshResponse {
    /**
     * 
     * @type {AuthUser}
     * @memberof AuthRefreshResponse
     */
    user?: AuthUser;
}

/**
 * Check if a given object implements the AuthRefreshResponse interface.
 */
export function instanceOfAuthRefreshResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AuthRefreshResponseFromJSON(json: any): AuthRefreshResponse {
    return AuthRefreshResponseFromJSONTyped(json, false);
}

export function AuthRefreshResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthRefreshResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': !exists(json, 'user') ? undefined : AuthUserFromJSON(json['user']),
    };
}

export function AuthRefreshResponseToJSON(value?: AuthRefreshResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': AuthUserToJSON(value.user),
    };
}

