/* tslint:disable */
/* eslint-disable */
/**
 * test
 * Your custom SDK
 *
 * The version of the OpenAPI document: test: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AuthLoginMetadata } from './AuthLoginMetadata';
import {
    AuthLoginMetadataFromJSON,
    AuthLoginMetadataFromJSONTyped,
    AuthLoginMetadataToJSON,
} from './AuthLoginMetadata';

/**
 * 
 * @export
 * @interface AuthRefreshRequest
 */
export interface AuthRefreshRequest {
    /**
     * 
     * @type {AuthLoginMetadata}
     * @memberof AuthRefreshRequest
     */
    loginMetadata?: AuthLoginMetadata;
    /**
     * Session token to refresh
     * @type {string}
     * @memberof AuthRefreshRequest
     */
    sessionToken: string;
}

/**
 * Check if a given object implements the AuthRefreshRequest interface.
 */
export function instanceOfAuthRefreshRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "sessionToken" in value;

    return isInstance;
}

export function AuthRefreshRequestFromJSON(json: any): AuthRefreshRequest {
    return AuthRefreshRequestFromJSONTyped(json, false);
}

export function AuthRefreshRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthRefreshRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'loginMetadata': !exists(json, 'login_metadata') ? undefined : AuthLoginMetadataFromJSON(json['login_metadata']),
        'sessionToken': json['session_token'],
    };
}

export function AuthRefreshRequestToJSON(value?: AuthRefreshRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'login_metadata': AuthLoginMetadataToJSON(value.loginMetadata),
        'session_token': value.sessionToken,
    };
}

