/* tslint:disable */
/* eslint-disable */
/**
 * lap-legend-race-game
 * Your custom SDK
 *
 * The version of the OpenAPI document: lap-legend-race-game: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthAppleLoginRequest
 */
export interface AuthAppleLoginRequest {
    /**
     * Whether to create a user, if it does not exist
     * @type {boolean}
     * @memberof AuthAppleLoginRequest
     */
    createUser?: boolean;
    /**
     * Apple token generated on the client
     * @type {string}
     * @memberof AuthAppleLoginRequest
     */
    token: string;
}

/**
 * Check if a given object implements the AuthAppleLoginRequest interface.
 */
export function instanceOfAuthAppleLoginRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "token" in value;

    return isInstance;
}

export function AuthAppleLoginRequestFromJSON(json: any): AuthAppleLoginRequest {
    return AuthAppleLoginRequestFromJSONTyped(json, false);
}

export function AuthAppleLoginRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthAppleLoginRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createUser': !exists(json, 'create_user') ? undefined : json['create_user'],
        'token': json['token'],
    };
}

export function AuthAppleLoginRequestToJSON(value?: AuthAppleLoginRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'create_user': value.createUser,
        'token': value.token,
    };
}

