/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v6 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AuthUser } from './AuthUser';
import {
    AuthUserFromJSON,
    AuthUserFromJSONTyped,
    AuthUserToJSON,
} from './AuthUser';

/**
 * 
 * @export
 * @interface AuthValidateResponse
 */
export interface AuthValidateResponse {
    /**
     * 
     * @type {AuthUser}
     * @memberof AuthValidateResponse
     */
    user?: AuthUser;
}

/**
 * Check if a given object implements the AuthValidateResponse interface.
 */
export function instanceOfAuthValidateResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AuthValidateResponseFromJSON(json: any): AuthValidateResponse {
    return AuthValidateResponseFromJSONTyped(json, false);
}

export function AuthValidateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthValidateResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': !exists(json, 'user') ? undefined : AuthUserFromJSON(json['user']),
    };
}

export function AuthValidateResponseToJSON(value?: AuthValidateResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': AuthUserToJSON(value.user),
    };
}

