/* tslint:disable */
/* eslint-disable */
/**
 * lap-legend-race-game
 * Your custom SDK
 *
 * The version of the OpenAPI document: lap-legend-race-game: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AuthUser } from './AuthUser';
import {
    AuthUserFromJSON,
    AuthUserFromJSONTyped,
    AuthUserToJSON,
} from './AuthUser';

/**
 * 
 * @export
 * @interface AuthFacebookLoginResponse
 */
export interface AuthFacebookLoginResponse {
    /**
     * 
     * @type {AuthUser}
     * @memberof AuthFacebookLoginResponse
     */
    user?: AuthUser;
}

/**
 * Check if a given object implements the AuthFacebookLoginResponse interface.
 */
export function instanceOfAuthFacebookLoginResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AuthFacebookLoginResponseFromJSON(json: any): AuthFacebookLoginResponse {
    return AuthFacebookLoginResponseFromJSONTyped(json, false);
}

export function AuthFacebookLoginResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthFacebookLoginResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': !exists(json, 'user') ? undefined : AuthUserFromJSON(json['user']),
    };
}

export function AuthFacebookLoginResponseToJSON(value?: AuthFacebookLoginResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': AuthUserToJSON(value.user),
    };
}

