/* tslint:disable */
/* eslint-disable */
/**
 * test
 * Your custom SDK
 *
 * The version of the OpenAPI document: test: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AuthUser } from './AuthUser';
import {
    AuthUserFromJSON,
    AuthUserFromJSONTyped,
    AuthUserToJSON,
} from './AuthUser';

/**
 * 
 * @export
 * @interface AuthEmailPasswordLoginResponse
 */
export interface AuthEmailPasswordLoginResponse {
    /**
     * Whether email verification is required or not
     * @type {boolean}
     * @memberof AuthEmailPasswordLoginResponse
     */
    emailVerificationRequired?: boolean;
    /**
     * 
     * @type {AuthUser}
     * @memberof AuthEmailPasswordLoginResponse
     */
    user?: AuthUser;
}

/**
 * Check if a given object implements the AuthEmailPasswordLoginResponse interface.
 */
export function instanceOfAuthEmailPasswordLoginResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AuthEmailPasswordLoginResponseFromJSON(json: any): AuthEmailPasswordLoginResponse {
    return AuthEmailPasswordLoginResponseFromJSONTyped(json, false);
}

export function AuthEmailPasswordLoginResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthEmailPasswordLoginResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'emailVerificationRequired': !exists(json, 'email_verification_required') ? undefined : json['email_verification_required'],
        'user': !exists(json, 'user') ? undefined : AuthUserFromJSON(json['user']),
    };
}

export function AuthEmailPasswordLoginResponseToJSON(value?: AuthEmailPasswordLoginResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email_verification_required': value.emailVerificationRequired,
        'user': AuthUserToJSON(value.user),
    };
}

