/* tslint:disable */
/* eslint-disable */
/**
 * test
 * Your custom SDK
 *
 * The version of the OpenAPI document: test: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthValidateRequest
 */
export interface AuthValidateRequest {
    /**
     * HTTP method of the request to your backend (OPTIONAL: required to validate user auth restrictions)
     * @type {string}
     * @memberof AuthValidateRequest
     */
    method?: string;
    /**
     * Path of the request to your backend (OPTIONAL: required to validate user auth restrictions)
     * @type {string}
     * @memberof AuthValidateRequest
     */
    path?: string;
    /**
     * Session token to validate
     * @type {string}
     * @memberof AuthValidateRequest
     */
    sessionToken: string;
}

/**
 * Check if a given object implements the AuthValidateRequest interface.
 */
export function instanceOfAuthValidateRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "sessionToken" in value;

    return isInstance;
}

export function AuthValidateRequestFromJSON(json: any): AuthValidateRequest {
    return AuthValidateRequestFromJSONTyped(json, false);
}

export function AuthValidateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthValidateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'method': !exists(json, 'method') ? undefined : json['method'],
        'path': !exists(json, 'path') ? undefined : json['path'],
        'sessionToken': json['session_token'],
    };
}

export function AuthValidateRequestToJSON(value?: AuthValidateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'method': value.method,
        'path': value.path,
        'session_token': value.sessionToken,
    };
}

