/* tslint:disable */
/* eslint-disable */
/**
 * test
 * Your custom SDK
 *
 * The version of the OpenAPI document: test: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AuthUser } from './AuthUser';
import {
    AuthUserFromJSON,
    AuthUserFromJSONTyped,
    AuthUserToJSON,
} from './AuthUser';

/**
 * 
 * @export
 * @interface AuthXLoginResponse
 */
export interface AuthXLoginResponse {
    /**
     * 
     * @type {AuthUser}
     * @memberof AuthXLoginResponse
     */
    user?: AuthUser;
}

/**
 * Check if a given object implements the AuthXLoginResponse interface.
 */
export function instanceOfAuthXLoginResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AuthXLoginResponseFromJSON(json: any): AuthXLoginResponse {
    return AuthXLoginResponseFromJSONTyped(json, false);
}

export function AuthXLoginResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthXLoginResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': !exists(json, 'user') ? undefined : AuthUserFromJSON(json['user']),
    };
}

export function AuthXLoginResponseToJSON(value?: AuthXLoginResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': AuthUserToJSON(value.user),
    };
}

