/* tslint:disable */
/* eslint-disable */
/**
 * lap-legend-race-game
 * Your custom SDK
 *
 * The version of the OpenAPI document: lap-legend-race-game: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthSteamOpenIdLoginRequest
 */
export interface AuthSteamOpenIdLoginRequest {
    /**
     * Whether to create a user, if it does not exist
     * @type {boolean}
     * @memberof AuthSteamOpenIdLoginRequest
     */
    createUser?: boolean;
    /**
     * Key value pairs of the openid parameters
     * @type {{ [key: string]: string; }}
     * @memberof AuthSteamOpenIdLoginRequest
     */
    openidParameters: { [key: string]: string; };
}

/**
 * Check if a given object implements the AuthSteamOpenIdLoginRequest interface.
 */
export function instanceOfAuthSteamOpenIdLoginRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "openidParameters" in value;

    return isInstance;
}

export function AuthSteamOpenIdLoginRequestFromJSON(json: any): AuthSteamOpenIdLoginRequest {
    return AuthSteamOpenIdLoginRequestFromJSONTyped(json, false);
}

export function AuthSteamOpenIdLoginRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthSteamOpenIdLoginRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createUser': !exists(json, 'create_user') ? undefined : json['create_user'],
        'openidParameters': json['openid_parameters'],
    };
}

export function AuthSteamOpenIdLoginRequestToJSON(value?: AuthSteamOpenIdLoginRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'create_user': value.createUser,
        'openid_parameters': value.openidParameters,
    };
}

