/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v6 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AuthLoginMetadata } from './AuthLoginMetadata';
import {
    AuthLoginMetadataFromJSON,
    AuthLoginMetadataFromJSONTyped,
    AuthLoginMetadataToJSON,
} from './AuthLoginMetadata';

/**
 * 
 * @export
 * @interface AuthXLoginRequest
 */
export interface AuthXLoginRequest {
    /**
     * X access token generated on the client. One of code or access_token is required
     * @type {string}
     * @memberof AuthXLoginRequest
     */
    accessToken?: string;
    /**
     * X code generated on the client. One of code or access_token is required
     * @type {string}
     * @memberof AuthXLoginRequest
     */
    code?: string;
    /**
     * X code verifier generated on the client
     * @type {string}
     * @memberof AuthXLoginRequest
     */
    codeVerifier?: string;
    /**
     * Whether to create a user, if it does not exist
     * @type {boolean}
     * @memberof AuthXLoginRequest
     */
    createUser?: boolean;
    /**
     * 
     * @type {AuthLoginMetadata}
     * @memberof AuthXLoginRequest
     */
    loginMetadata?: AuthLoginMetadata;
    /**
     * redirect url for client
     * @type {string}
     * @memberof AuthXLoginRequest
     */
    redirectUri?: string;
}

/**
 * Check if a given object implements the AuthXLoginRequest interface.
 */
export function instanceOfAuthXLoginRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AuthXLoginRequestFromJSON(json: any): AuthXLoginRequest {
    return AuthXLoginRequestFromJSONTyped(json, false);
}

export function AuthXLoginRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthXLoginRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessToken': !exists(json, 'access_token') ? undefined : json['access_token'],
        'code': !exists(json, 'code') ? undefined : json['code'],
        'codeVerifier': !exists(json, 'code_verifier') ? undefined : json['code_verifier'],
        'createUser': !exists(json, 'create_user') ? undefined : json['create_user'],
        'loginMetadata': !exists(json, 'login_metadata') ? undefined : AuthLoginMetadataFromJSON(json['login_metadata']),
        'redirectUri': !exists(json, 'redirect_uri') ? undefined : json['redirect_uri'],
    };
}

export function AuthXLoginRequestToJSON(value?: AuthXLoginRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'access_token': value.accessToken,
        'code': value.code,
        'code_verifier': value.codeVerifier,
        'create_user': value.createUser,
        'login_metadata': AuthLoginMetadataToJSON(value.loginMetadata),
        'redirect_uri': value.redirectUri,
    };
}

