/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v6 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AuthLoginTypeType } from './AuthLoginTypeType';
import {
    AuthLoginTypeTypeFromJSON,
    AuthLoginTypeTypeFromJSONTyped,
    AuthLoginTypeTypeToJSON,
} from './AuthLoginTypeType';

/**
 * 
 * @export
 * @interface AuthLoginId
 */
export interface AuthLoginId {
    /**
     * 
     * @type {string}
     * @memberof AuthLoginId
     */
    id?: string;
    /**
     * 
     * @type {AuthLoginTypeType}
     * @memberof AuthLoginId
     */
    type?: AuthLoginTypeType;
}

/**
 * Check if a given object implements the AuthLoginId interface.
 */
export function instanceOfAuthLoginId(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AuthLoginIdFromJSON(json: any): AuthLoginId {
    return AuthLoginIdFromJSONTyped(json, false);
}

export function AuthLoginIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthLoginId {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'type': !exists(json, 'type') ? undefined : AuthLoginTypeTypeFromJSON(json['type']),
    };
}

export function AuthLoginIdToJSON(value?: AuthLoginId | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'type': AuthLoginTypeTypeToJSON(value.type),
    };
}

