/* tslint:disable */
/* eslint-disable */
/**
 * lap-legend-race-game
 * Your custom SDK
 *
 * The version of the OpenAPI document: lap-legend-race-game: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthAnonLoginRequest
 */
export interface AuthAnonLoginRequest {
    /**
     * Whether to create a user, if it does not exist
     * @type {boolean}
     * @memberof AuthAnonLoginRequest
     */
    createUser?: boolean;
    /**
     * User's login ID
     * @type {string}
     * @memberof AuthAnonLoginRequest
     */
    username: string;
}

/**
 * Check if a given object implements the AuthAnonLoginRequest interface.
 */
export function instanceOfAuthAnonLoginRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "username" in value;

    return isInstance;
}

export function AuthAnonLoginRequestFromJSON(json: any): AuthAnonLoginRequest {
    return AuthAnonLoginRequestFromJSONTyped(json, false);
}

export function AuthAnonLoginRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthAnonLoginRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createUser': !exists(json, 'create_user') ? undefined : json['create_user'],
        'username': json['username'],
    };
}

export function AuthAnonLoginRequestToJSON(value?: AuthAnonLoginRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'create_user': value.createUser,
        'username': value.username,
    };
}

