/* tslint:disable */
/* eslint-disable */
/**
 * lap-legend-race-game
 * Your custom SDK
 *
 * The version of the OpenAPI document: lap-legend-race-game: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthSteamSessionTicketLoginRequest
 */
export interface AuthSteamSessionTicketLoginRequest {
    /**
     * Whether to create a user, if it does not exist
     * @type {boolean}
     * @memberof AuthSteamSessionTicketLoginRequest
     */
    createUser?: boolean;
    /**
     * Identity string used to generate session ticket (if applicable)
     * @type {string}
     * @memberof AuthSteamSessionTicketLoginRequest
     */
    identity?: string;
    /**
     * Session ticket generated on the client
     * @type {string}
     * @memberof AuthSteamSessionTicketLoginRequest
     */
    sessionTicket: string;
}

/**
 * Check if a given object implements the AuthSteamSessionTicketLoginRequest interface.
 */
export function instanceOfAuthSteamSessionTicketLoginRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "sessionTicket" in value;

    return isInstance;
}

export function AuthSteamSessionTicketLoginRequestFromJSON(json: any): AuthSteamSessionTicketLoginRequest {
    return AuthSteamSessionTicketLoginRequestFromJSONTyped(json, false);
}

export function AuthSteamSessionTicketLoginRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthSteamSessionTicketLoginRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createUser': !exists(json, 'create_user') ? undefined : json['create_user'],
        'identity': !exists(json, 'identity') ? undefined : json['identity'],
        'sessionTicket': json['session_ticket'],
    };
}

export function AuthSteamSessionTicketLoginRequestToJSON(value?: AuthSteamSessionTicketLoginRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'create_user': value.createUser,
        'identity': value.identity,
        'session_ticket': value.sessionTicket,
    };
}

