/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v6 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AuthLoginMetadata } from './AuthLoginMetadata';
import {
    AuthLoginMetadataFromJSON,
    AuthLoginMetadataFromJSONTyped,
    AuthLoginMetadataToJSON,
} from './AuthLoginMetadata';

/**
 * 
 * @export
 * @interface AuthSteamOpenIdLoginRequest
 */
export interface AuthSteamOpenIdLoginRequest {
    /**
     * Whether to create a user, if it does not exist
     * @type {boolean}
     * @memberof AuthSteamOpenIdLoginRequest
     */
    createUser?: boolean;
    /**
     * 
     * @type {AuthLoginMetadata}
     * @memberof AuthSteamOpenIdLoginRequest
     */
    loginMetadata?: AuthLoginMetadata;
    /**
     * Key value pairs of the openid parameters
     * @type {{ [key: string]: string; }}
     * @memberof AuthSteamOpenIdLoginRequest
     */
    openidParameters: { [key: string]: string; };
}

/**
 * Check if a given object implements the AuthSteamOpenIdLoginRequest interface.
 */
export function instanceOfAuthSteamOpenIdLoginRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "openidParameters" in value;

    return isInstance;
}

export function AuthSteamOpenIdLoginRequestFromJSON(json: any): AuthSteamOpenIdLoginRequest {
    return AuthSteamOpenIdLoginRequestFromJSONTyped(json, false);
}

export function AuthSteamOpenIdLoginRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthSteamOpenIdLoginRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createUser': !exists(json, 'create_user') ? undefined : json['create_user'],
        'loginMetadata': !exists(json, 'login_metadata') ? undefined : AuthLoginMetadataFromJSON(json['login_metadata']),
        'openidParameters': json['openid_parameters'],
    };
}

export function AuthSteamOpenIdLoginRequestToJSON(value?: AuthSteamOpenIdLoginRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'create_user': value.createUser,
        'login_metadata': AuthLoginMetadataToJSON(value.loginMetadata),
        'openid_parameters': value.openidParameters,
    };
}

