/* tslint:disable */
/* eslint-disable */
/**
 * lap-legend-race-game
 * Your custom SDK
 *
 * The version of the OpenAPI document: lap-legend-race-game: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthEmailPasswordLoginRequest
 */
export interface AuthEmailPasswordLoginRequest {
    /**
     * Whether to create a user, if it does not exist
     * @type {boolean}
     * @memberof AuthEmailPasswordLoginRequest
     */
    createUser?: boolean;
    /**
     * Email address used as login
     * @type {string}
     * @memberof AuthEmailPasswordLoginRequest
     */
    email: string;
    /**
     * Password used for login
     * @type {string}
     * @memberof AuthEmailPasswordLoginRequest
     */
    password: string;
}

/**
 * Check if a given object implements the AuthEmailPasswordLoginRequest interface.
 */
export function instanceOfAuthEmailPasswordLoginRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function AuthEmailPasswordLoginRequestFromJSON(json: any): AuthEmailPasswordLoginRequest {
    return AuthEmailPasswordLoginRequestFromJSONTyped(json, false);
}

export function AuthEmailPasswordLoginRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthEmailPasswordLoginRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createUser': !exists(json, 'create_user') ? undefined : json['create_user'],
        'email': json['email'],
        'password': json['password'],
    };
}

export function AuthEmailPasswordLoginRequestToJSON(value?: AuthEmailPasswordLoginRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'create_user': value.createUser,
        'email': value.email,
        'password': value.password,
    };
}

