/* tslint:disable */
/* eslint-disable */
/**
 * lap-legend-race-game
 * Your custom SDK
 *
 * The version of the OpenAPI document: lap-legend-race-game: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthEpicLoginRequest
 */
export interface AuthEpicLoginRequest {
    /**
     * code generated on the client
     * @type {string}
     * @memberof AuthEpicLoginRequest
     */
    code?: string;
    /**
     * Whether to create a user, if it does not exist
     * @type {boolean}
     * @memberof AuthEpicLoginRequest
     */
    createUser?: boolean;
    /**
     * exchange_code generated on the client
     * @type {string}
     * @memberof AuthEpicLoginRequest
     */
    exchangeCode?: string;
    /**
     * token generated on the client
     * @type {string}
     * @memberof AuthEpicLoginRequest
     */
    grantType: string;
    /**
     * exchange_code generated on the client
     * @type {string}
     * @memberof AuthEpicLoginRequest
     */
    password?: string;
    /**
     * exchange_code generated on the client
     * @type {string}
     * @memberof AuthEpicLoginRequest
     */
    username?: string;
}

/**
 * Check if a given object implements the AuthEpicLoginRequest interface.
 */
export function instanceOfAuthEpicLoginRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "grantType" in value;

    return isInstance;
}

export function AuthEpicLoginRequestFromJSON(json: any): AuthEpicLoginRequest {
    return AuthEpicLoginRequestFromJSONTyped(json, false);
}

export function AuthEpicLoginRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthEpicLoginRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'createUser': !exists(json, 'create_user') ? undefined : json['create_user'],
        'exchangeCode': !exists(json, 'exchange_code') ? undefined : json['exchange_code'],
        'grantType': json['grant_type'],
        'password': !exists(json, 'password') ? undefined : json['password'],
        'username': !exists(json, 'username') ? undefined : json['username'],
    };
}

export function AuthEpicLoginRequestToJSON(value?: AuthEpicLoginRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'create_user': value.createUser,
        'exchange_code': value.exchangeCode,
        'grant_type': value.grantType,
        'password': value.password,
        'username': value.username,
    };
}

