/* tslint:disable */
/* eslint-disable */
/**
 * lap-legend-race-game
 * Your custom SDK
 *
 * The version of the OpenAPI document: lap-legend-race-game: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthDiscordLoginRequest
 */
export interface AuthDiscordLoginRequest {
    /**
     * Discord access token generated on the client. One of code or access_token is required
     * @type {string}
     * @memberof AuthDiscordLoginRequest
     */
    accessToken?: string;
    /**
     * Discord code generated on the client. One of code or access_token is required
     * @type {string}
     * @memberof AuthDiscordLoginRequest
     */
    code?: string;
    /**
     * Whether to create a user, if it does not exist
     * @type {boolean}
     * @memberof AuthDiscordLoginRequest
     */
    createUser?: boolean;
}

/**
 * Check if a given object implements the AuthDiscordLoginRequest interface.
 */
export function instanceOfAuthDiscordLoginRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AuthDiscordLoginRequestFromJSON(json: any): AuthDiscordLoginRequest {
    return AuthDiscordLoginRequestFromJSONTyped(json, false);
}

export function AuthDiscordLoginRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthDiscordLoginRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessToken': !exists(json, 'access_token') ? undefined : json['access_token'],
        'code': !exists(json, 'code') ? undefined : json['code'],
        'createUser': !exists(json, 'create_user') ? undefined : json['create_user'],
    };
}

export function AuthDiscordLoginRequestToJSON(value?: AuthDiscordLoginRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'access_token': value.accessToken,
        'code': value.code,
        'create_user': value.createUser,
    };
}

