/* tslint:disable */
/* eslint-disable */
/**
 * test
 * Your custom SDK
 *
 * The version of the OpenAPI document: test: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthSuspendUserResponse
 */
export interface AuthSuspendUserResponse {
    /**
     * Timestamp until which the user is suspended
     * @type {number}
     * @memberof AuthSuspendUserResponse
     */
    suspendedUntil?: number;
}

/**
 * Check if a given object implements the AuthSuspendUserResponse interface.
 */
export function instanceOfAuthSuspendUserResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AuthSuspendUserResponseFromJSON(json: any): AuthSuspendUserResponse {
    return AuthSuspendUserResponseFromJSONTyped(json, false);
}

export function AuthSuspendUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthSuspendUserResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'suspendedUntil': !exists(json, 'suspended_until') ? undefined : json['suspended_until'],
    };
}

export function AuthSuspendUserResponseToJSON(value?: AuthSuspendUserResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'suspended_until': value.suspendedUntil,
    };
}

