/* tslint:disable */
/* eslint-disable */
/**
 * lap-legend-race-game
 * Your custom SDK
 *
 * The version of the OpenAPI document: lap-legend-race-game: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthXboxLoginRequest
 */
export interface AuthXboxLoginRequest {
    /**
     * code generated on the client
     * @type {string}
     * @memberof AuthXboxLoginRequest
     */
    code: string;
    /**
     * Whether to create a user, if it does not exist
     * @type {boolean}
     * @memberof AuthXboxLoginRequest
     */
    createUser?: boolean;
    /**
     * redirect url for client
     * @type {string}
     * @memberof AuthXboxLoginRequest
     */
    redirectUrl: string;
}

/**
 * Check if a given object implements the AuthXboxLoginRequest interface.
 */
export function instanceOfAuthXboxLoginRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "code" in value;
    isInstance = isInstance && "redirectUrl" in value;

    return isInstance;
}

export function AuthXboxLoginRequestFromJSON(json: any): AuthXboxLoginRequest {
    return AuthXboxLoginRequestFromJSONTyped(json, false);
}

export function AuthXboxLoginRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthXboxLoginRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
        'createUser': !exists(json, 'create_user') ? undefined : json['create_user'],
        'redirectUrl': json['redirect_url'],
    };
}

export function AuthXboxLoginRequestToJSON(value?: AuthXboxLoginRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'create_user': value.createUser,
        'redirect_url': value.redirectUrl,
    };
}

