/* tslint:disable */
/* eslint-disable */
/**
 * lap-legend-race-game
 * Your custom SDK
 *
 * The version of the OpenAPI document: lap-legend-race-game: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DisassociateLoginRequest
 */
export interface DisassociateLoginRequest {
    /**
     * Login type
     * @type {string}
     * @memberof DisassociateLoginRequest
     */
    loginType: string;
}

/**
 * Check if a given object implements the DisassociateLoginRequest interface.
 */
export function instanceOfDisassociateLoginRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "loginType" in value;

    return isInstance;
}

export function DisassociateLoginRequestFromJSON(json: any): DisassociateLoginRequest {
    return DisassociateLoginRequestFromJSONTyped(json, false);
}

export function DisassociateLoginRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DisassociateLoginRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'loginType': json['login_type'],
    };
}

export function DisassociateLoginRequestToJSON(value?: DisassociateLoginRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'login_type': value.loginType,
    };
}

