/* tslint:disable */
/* eslint-disable */
/**
 * test
 * Your custom SDK
 *
 * The version of the OpenAPI document: test: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IncrementCounterRequest
 */
export interface IncrementCounterRequest {
    /**
     * Value to increment the counter by. Use negative to decrement
     * @type {number}
     * @memberof IncrementCounterRequest
     */
    count: number;
}

/**
 * Check if a given object implements the IncrementCounterRequest interface.
 */
export function instanceOfIncrementCounterRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "count" in value;

    return isInstance;
}

export function IncrementCounterRequestFromJSON(json: any): IncrementCounterRequest {
    return IncrementCounterRequestFromJSONTyped(json, false);
}

export function IncrementCounterRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncrementCounterRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': json['count'],
    };
}

export function IncrementCounterRequestToJSON(value?: IncrementCounterRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
    };
}

