/* tslint:disable */
/* eslint-disable */
/**
 * test
 * Your custom SDK
 *
 * The version of the OpenAPI document: test: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InsertBlobRequest
 */
export interface InsertBlobRequest {
    /**
     * Optional TTL for the blob
     * @type {number}
     * @memberof InsertBlobRequest
     */
    ttl?: number;
    /**
     * Blob value to be inserted
     * @type {string}
     * @memberof InsertBlobRequest
     */
    value: string;
}

/**
 * Check if a given object implements the InsertBlobRequest interface.
 */
export function instanceOfInsertBlobRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function InsertBlobRequestFromJSON(json: any): InsertBlobRequest {
    return InsertBlobRequestFromJSONTyped(json, false);
}

export function InsertBlobRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): InsertBlobRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ttl': !exists(json, 'ttl') ? undefined : json['ttl'],
        'value': json['value'],
    };
}

export function InsertBlobRequestToJSON(value?: InsertBlobRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ttl': value.ttl,
        'value': value.value,
    };
}

