/* tslint:disable */
/* eslint-disable */
/**
 * test
 * Your custom SDK
 *
 * The version of the OpenAPI document: test: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InsertJsonBlobRequest
 */
export interface InsertJsonBlobRequest {
    /**
     * Optional TTL for the blob
     * @type {number}
     * @memberof InsertJsonBlobRequest
     */
    ttl?: number;
    /**
     * JSON value to be inserted
     * @type {object}
     * @memberof InsertJsonBlobRequest
     */
    value: object;
}

/**
 * Check if a given object implements the InsertJsonBlobRequest interface.
 */
export function instanceOfInsertJsonBlobRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function InsertJsonBlobRequestFromJSON(json: any): InsertJsonBlobRequest {
    return InsertJsonBlobRequestFromJSONTyped(json, false);
}

export function InsertJsonBlobRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): InsertJsonBlobRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ttl': !exists(json, 'ttl') ? undefined : json['ttl'],
        'value': json['value'],
    };
}

export function InsertJsonBlobRequestToJSON(value?: InsertJsonBlobRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ttl': value.ttl,
        'value': value.value,
    };
}

