/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v6 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LeaderboardsSetScoreRequest
 */
export interface LeaderboardsSetScoreRequest {
    /**
     * Name of the leaderboard
     * @type {string}
     * @memberof LeaderboardsSetScoreRequest
     */
    leaderboardName: string;
    /**
     * New score to be inserted
     * @type {number}
     * @memberof LeaderboardsSetScoreRequest
     */
    score: number;
    /**
     * Name of the tier
     * @type {string}
     * @memberof LeaderboardsSetScoreRequest
     */
    tierName?: string;
    /**
     * User ID for the user who's score is being updated
     * @type {string}
     * @memberof LeaderboardsSetScoreRequest
     */
    userId: string;
    /**
     * Metadata to be stored with the user
     * @type {object}
     * @memberof LeaderboardsSetScoreRequest
     */
    userMetadata?: object;
}

/**
 * Check if a given object implements the LeaderboardsSetScoreRequest interface.
 */
export function instanceOfLeaderboardsSetScoreRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "leaderboardName" in value;
    isInstance = isInstance && "score" in value;
    isInstance = isInstance && "userId" in value;

    return isInstance;
}

export function LeaderboardsSetScoreRequestFromJSON(json: any): LeaderboardsSetScoreRequest {
    return LeaderboardsSetScoreRequestFromJSONTyped(json, false);
}

export function LeaderboardsSetScoreRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LeaderboardsSetScoreRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'leaderboardName': json['leaderboard_name'],
        'score': json['score'],
        'tierName': !exists(json, 'tier_name') ? undefined : json['tier_name'],
        'userId': json['user_id'],
        'userMetadata': !exists(json, 'user_metadata') ? undefined : json['user_metadata'],
    };
}

export function LeaderboardsSetScoreRequestToJSON(value?: LeaderboardsSetScoreRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'leaderboard_name': value.leaderboardName,
        'score': value.score,
        'tier_name': value.tierName,
        'user_id': value.userId,
        'user_metadata': value.userMetadata,
    };
}

