/* tslint:disable */
/* eslint-disable */
/**
 * lap-legend-race-game
 * Your custom SDK
 *
 * The version of the OpenAPI document: lap-legend-race-game: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LeaderboardsGetScoresRequest } from './LeaderboardsGetScoresRequest';
import {
    LeaderboardsGetScoresRequestFromJSON,
    LeaderboardsGetScoresRequestFromJSONTyped,
    LeaderboardsGetScoresRequestToJSON,
} from './LeaderboardsGetScoresRequest';
import type { LeaderboardsTieredUserScore } from './LeaderboardsTieredUserScore';
import {
    LeaderboardsTieredUserScoreFromJSON,
    LeaderboardsTieredUserScoreFromJSONTyped,
    LeaderboardsTieredUserScoreToJSON,
} from './LeaderboardsTieredUserScore';

/**
 * 
 * @export
 * @interface LeaderboardsBatchGetScoresSingleResponse
 */
export interface LeaderboardsBatchGetScoresSingleResponse {
    /**
     * 
     * @type {string}
     * @memberof LeaderboardsBatchGetScoresSingleResponse
     */
    message?: string;
    /**
     * 
     * @type {LeaderboardsGetScoresRequest}
     * @memberof LeaderboardsBatchGetScoresSingleResponse
     */
    request?: LeaderboardsGetScoresRequest;
    /**
     * 
     * @type {Array<LeaderboardsTieredUserScore>}
     * @memberof LeaderboardsBatchGetScoresSingleResponse
     */
    response?: Array<LeaderboardsTieredUserScore>;
    /**
     * 
     * @type {boolean}
     * @memberof LeaderboardsBatchGetScoresSingleResponse
     */
    success?: boolean;
}

/**
 * Check if a given object implements the LeaderboardsBatchGetScoresSingleResponse interface.
 */
export function instanceOfLeaderboardsBatchGetScoresSingleResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LeaderboardsBatchGetScoresSingleResponseFromJSON(json: any): LeaderboardsBatchGetScoresSingleResponse {
    return LeaderboardsBatchGetScoresSingleResponseFromJSONTyped(json, false);
}

export function LeaderboardsBatchGetScoresSingleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LeaderboardsBatchGetScoresSingleResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
        'request': !exists(json, 'request') ? undefined : LeaderboardsGetScoresRequestFromJSON(json['request']),
        'response': !exists(json, 'response') ? undefined : ((json['response'] as Array<any>).map(LeaderboardsTieredUserScoreFromJSON)),
        'success': !exists(json, 'success') ? undefined : json['success'],
    };
}

export function LeaderboardsBatchGetScoresSingleResponseToJSON(value?: LeaderboardsBatchGetScoresSingleResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'request': LeaderboardsGetScoresRequestToJSON(value.request),
        'response': value.response === undefined ? undefined : ((value.response as Array<any>).map(LeaderboardsTieredUserScoreToJSON)),
        'success': value.success,
    };
}

