/* tslint:disable */
/* eslint-disable */
/**
 * test
 * Your custom SDK
 *
 * The version of the OpenAPI document: test: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LeaderboardsUserScore } from './LeaderboardsUserScore';
import {
    LeaderboardsUserScoreFromJSON,
    LeaderboardsUserScoreFromJSONTyped,
    LeaderboardsUserScoreToJSON,
} from './LeaderboardsUserScore';

/**
 * 
 * @export
 * @interface LeaderboardsTieredUserScore
 */
export interface LeaderboardsTieredUserScore {
    /**
     * Name of the tier
     * @type {string}
     * @memberof LeaderboardsTieredUserScore
     */
    tier?: string;
    /**
     * 
     * @type {LeaderboardsUserScore}
     * @memberof LeaderboardsTieredUserScore
     */
    userScore?: LeaderboardsUserScore;
}

/**
 * Check if a given object implements the LeaderboardsTieredUserScore interface.
 */
export function instanceOfLeaderboardsTieredUserScore(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LeaderboardsTieredUserScoreFromJSON(json: any): LeaderboardsTieredUserScore {
    return LeaderboardsTieredUserScoreFromJSONTyped(json, false);
}

export function LeaderboardsTieredUserScoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): LeaderboardsTieredUserScore {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tier': !exists(json, 'tier') ? undefined : json['tier'],
        'userScore': !exists(json, 'user_score') ? undefined : LeaderboardsUserScoreFromJSON(json['user_score']),
    };
}

export function LeaderboardsTieredUserScoreToJSON(value?: LeaderboardsTieredUserScore | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tier': value.tier,
        'user_score': LeaderboardsUserScoreToJSON(value.userScore),
    };
}

