/* tslint:disable */
/* eslint-disable */
/**
 * test
 * Your custom SDK
 *
 * The version of the OpenAPI document: test: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LeaderboardsSetScoreRequest } from './LeaderboardsSetScoreRequest';
import {
    LeaderboardsSetScoreRequestFromJSON,
    LeaderboardsSetScoreRequestFromJSONTyped,
    LeaderboardsSetScoreRequestToJSON,
} from './LeaderboardsSetScoreRequest';
import type { LeaderboardsSetScoreResponse } from './LeaderboardsSetScoreResponse';
import {
    LeaderboardsSetScoreResponseFromJSON,
    LeaderboardsSetScoreResponseFromJSONTyped,
    LeaderboardsSetScoreResponseToJSON,
} from './LeaderboardsSetScoreResponse';

/**
 * 
 * @export
 * @interface LeaderboardsBatchSetScoreSingleResponse
 */
export interface LeaderboardsBatchSetScoreSingleResponse {
    /**
     * 
     * @type {string}
     * @memberof LeaderboardsBatchSetScoreSingleResponse
     */
    message?: string;
    /**
     * 
     * @type {LeaderboardsSetScoreRequest}
     * @memberof LeaderboardsBatchSetScoreSingleResponse
     */
    request?: LeaderboardsSetScoreRequest;
    /**
     * 
     * @type {LeaderboardsSetScoreResponse}
     * @memberof LeaderboardsBatchSetScoreSingleResponse
     */
    response?: LeaderboardsSetScoreResponse;
    /**
     * 
     * @type {boolean}
     * @memberof LeaderboardsBatchSetScoreSingleResponse
     */
    success?: boolean;
}

/**
 * Check if a given object implements the LeaderboardsBatchSetScoreSingleResponse interface.
 */
export function instanceOfLeaderboardsBatchSetScoreSingleResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LeaderboardsBatchSetScoreSingleResponseFromJSON(json: any): LeaderboardsBatchSetScoreSingleResponse {
    return LeaderboardsBatchSetScoreSingleResponseFromJSONTyped(json, false);
}

export function LeaderboardsBatchSetScoreSingleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LeaderboardsBatchSetScoreSingleResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
        'request': !exists(json, 'request') ? undefined : LeaderboardsSetScoreRequestFromJSON(json['request']),
        'response': !exists(json, 'response') ? undefined : LeaderboardsSetScoreResponseFromJSON(json['response']),
        'success': !exists(json, 'success') ? undefined : json['success'],
    };
}

export function LeaderboardsBatchSetScoreSingleResponseToJSON(value?: LeaderboardsBatchSetScoreSingleResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'request': LeaderboardsSetScoreRequestToJSON(value.request),
        'response': LeaderboardsSetScoreResponseToJSON(value.response),
        'success': value.success,
    };
}

