/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v6 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LeaderboardsTier
 */
export interface LeaderboardsTier {
    /**
     * 
     * @type {string}
     * @memberof LeaderboardsTier
     */
    bucketSize?: string;
    /**
     * 
     * @type {string}
     * @memberof LeaderboardsTier
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof LeaderboardsTier
     */
    name?: string;
}

/**
 * Check if a given object implements the LeaderboardsTier interface.
 */
export function instanceOfLeaderboardsTier(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LeaderboardsTierFromJSON(json: any): LeaderboardsTier {
    return LeaderboardsTierFromJSONTyped(json, false);
}

export function LeaderboardsTierFromJSONTyped(json: any, ignoreDiscriminator: boolean): LeaderboardsTier {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bucketSize': !exists(json, 'bucket_size') ? undefined : json['bucket_size'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function LeaderboardsTierToJSON(value?: LeaderboardsTier | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bucket_size': value.bucketSize,
        'description': value.description,
        'name': value.name,
    };
}

