/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v6 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LeaderboardsIncrementScoreRequest
 */
export interface LeaderboardsIncrementScoreRequest {
    /**
     * The delta of the score to increment
     * @type {number}
     * @memberof LeaderboardsIncrementScoreRequest
     */
    delta: number;
    /**
     * Name of the leaderboard
     * @type {string}
     * @memberof LeaderboardsIncrementScoreRequest
     */
    leaderboardName: string;
    /**
     * Name of the tier
     * @type {string}
     * @memberof LeaderboardsIncrementScoreRequest
     */
    tierName?: string;
    /**
     * User ID for the user who's score is being updated
     * @type {string}
     * @memberof LeaderboardsIncrementScoreRequest
     */
    userId: string;
    /**
     * Metadata to be stored with the user
     * @type {object}
     * @memberof LeaderboardsIncrementScoreRequest
     */
    userMetadata?: object;
}

/**
 * Check if a given object implements the LeaderboardsIncrementScoreRequest interface.
 */
export function instanceOfLeaderboardsIncrementScoreRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "delta" in value;
    isInstance = isInstance && "leaderboardName" in value;
    isInstance = isInstance && "userId" in value;

    return isInstance;
}

export function LeaderboardsIncrementScoreRequestFromJSON(json: any): LeaderboardsIncrementScoreRequest {
    return LeaderboardsIncrementScoreRequestFromJSONTyped(json, false);
}

export function LeaderboardsIncrementScoreRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LeaderboardsIncrementScoreRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'delta': json['delta'],
        'leaderboardName': json['leaderboard_name'],
        'tierName': !exists(json, 'tier_name') ? undefined : json['tier_name'],
        'userId': json['user_id'],
        'userMetadata': !exists(json, 'user_metadata') ? undefined : json['user_metadata'],
    };
}

export function LeaderboardsIncrementScoreRequestToJSON(value?: LeaderboardsIncrementScoreRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'delta': value.delta,
        'leaderboard_name': value.leaderboardName,
        'tier_name': value.tierName,
        'user_id': value.userId,
        'user_metadata': value.userMetadata,
    };
}

