/* tslint:disable */
/* eslint-disable */
/**
 * test
 * Your custom SDK
 *
 * The version of the OpenAPI document: test: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LeaderboardsTier } from './LeaderboardsTier';
import {
    LeaderboardsTierFromJSON,
    LeaderboardsTierFromJSONTyped,
    LeaderboardsTierToJSON,
} from './LeaderboardsTier';

/**
 * 
 * @export
 * @interface LeaderboardsSetScoreResponse
 */
export interface LeaderboardsSetScoreResponse {
    /**
     * Latest rank to be returned
     * @type {number}
     * @memberof LeaderboardsSetScoreResponse
     */
    rank?: number;
    /**
     * Latest score to be returned
     * @type {number}
     * @memberof LeaderboardsSetScoreResponse
     */
    score?: number;
    /**
     * 
     * @type {LeaderboardsTier}
     * @memberof LeaderboardsSetScoreResponse
     */
    tier?: LeaderboardsTier;
    /**
     * User ID of the user
     * @type {string}
     * @memberof LeaderboardsSetScoreResponse
     */
    userId?: string;
}

/**
 * Check if a given object implements the LeaderboardsSetScoreResponse interface.
 */
export function instanceOfLeaderboardsSetScoreResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LeaderboardsSetScoreResponseFromJSON(json: any): LeaderboardsSetScoreResponse {
    return LeaderboardsSetScoreResponseFromJSONTyped(json, false);
}

export function LeaderboardsSetScoreResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LeaderboardsSetScoreResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rank': !exists(json, 'rank') ? undefined : json['rank'],
        'score': !exists(json, 'score') ? undefined : json['score'],
        'tier': !exists(json, 'tier') ? undefined : LeaderboardsTierFromJSON(json['tier']),
        'userId': !exists(json, 'user_id') ? undefined : json['user_id'],
    };
}

export function LeaderboardsSetScoreResponseToJSON(value?: LeaderboardsSetScoreResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rank': value.rank,
        'score': value.score,
        'tier': LeaderboardsTierToJSON(value.tier),
        'user_id': value.userId,
    };
}

