/* tslint:disable */
/* eslint-disable */
/**
 * lap-legend-race-game
 * Your custom SDK
 *
 * The version of the OpenAPI document: lap-legend-race-game: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RemoteConfigGetAppConfigResponse
 */
export interface RemoteConfigGetAppConfigResponse {
    /**
     * Config for the app
     * @type {object}
     * @memberof RemoteConfigGetAppConfigResponse
     */
    config?: object;
}

/**
 * Check if a given object implements the RemoteConfigGetAppConfigResponse interface.
 */
export function instanceOfRemoteConfigGetAppConfigResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RemoteConfigGetAppConfigResponseFromJSON(json: any): RemoteConfigGetAppConfigResponse {
    return RemoteConfigGetAppConfigResponseFromJSONTyped(json, false);
}

export function RemoteConfigGetAppConfigResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RemoteConfigGetAppConfigResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'config': !exists(json, 'config') ? undefined : json['config'],
    };
}

export function RemoteConfigGetAppConfigResponseToJSON(value?: RemoteConfigGetAppConfigResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'config': value.config,
    };
}

