/* tslint:disable */
/* eslint-disable */
/**
 * lap-legend-race-game
 * Your custom SDK
 *
 * The version of the OpenAPI document: lap-legend-race-game: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RemoteConfigGetUserConfigResponse
 */
export interface RemoteConfigGetUserConfigResponse {
    /**
     * Config for the user
     * @type {object}
     * @memberof RemoteConfigGetUserConfigResponse
     */
    config?: object;
}

/**
 * Check if a given object implements the RemoteConfigGetUserConfigResponse interface.
 */
export function instanceOfRemoteConfigGetUserConfigResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RemoteConfigGetUserConfigResponseFromJSON(json: any): RemoteConfigGetUserConfigResponse {
    return RemoteConfigGetUserConfigResponseFromJSONTyped(json, false);
}

export function RemoteConfigGetUserConfigResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RemoteConfigGetUserConfigResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'config': !exists(json, 'config') ? undefined : json['config'],
    };
}

export function RemoteConfigGetUserConfigResponseToJSON(value?: RemoteConfigGetUserConfigResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'config': value.config,
    };
}

