/* tslint:disable */
/* eslint-disable */
/**
 * test
 * Your custom SDK
 *
 * The version of the OpenAPI document: test: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StorageGetJsonBlobRequest
 */
export interface StorageGetJsonBlobRequest {
    /**
     * Access to the blob. (public/protected/private)
     * @type {string}
     * @memberof StorageGetJsonBlobRequest
     */
    accessType: StorageGetJsonBlobRequestAccessTypeEnum;
    /**
     * Blob key
     * @type {string}
     * @memberof StorageGetJsonBlobRequest
     */
    jsonBlobKey: string;
    /**
     * Blob owner's user ID
     * @type {string}
     * @memberof StorageGetJsonBlobRequest
     */
    ownerId: string;
}


/**
 * @export
 */
export const StorageGetJsonBlobRequestAccessTypeEnum = {
    Public: 'public',
    Private: 'private',
    Protected: 'protected'
} as const;
export type StorageGetJsonBlobRequestAccessTypeEnum = typeof StorageGetJsonBlobRequestAccessTypeEnum[keyof typeof StorageGetJsonBlobRequestAccessTypeEnum];


/**
 * Check if a given object implements the StorageGetJsonBlobRequest interface.
 */
export function instanceOfStorageGetJsonBlobRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "accessType" in value;
    isInstance = isInstance && "jsonBlobKey" in value;
    isInstance = isInstance && "ownerId" in value;

    return isInstance;
}

export function StorageGetJsonBlobRequestFromJSON(json: any): StorageGetJsonBlobRequest {
    return StorageGetJsonBlobRequestFromJSONTyped(json, false);
}

export function StorageGetJsonBlobRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageGetJsonBlobRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessType': json['access_type'],
        'jsonBlobKey': json['json_blob_key'],
        'ownerId': json['owner_id'],
    };
}

export function StorageGetJsonBlobRequestToJSON(value?: StorageGetJsonBlobRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'access_type': value.accessType,
        'json_blob_key': value.jsonBlobKey,
        'owner_id': value.ownerId,
    };
}

