/* tslint:disable */
/* eslint-disable */
/**
 * lap-legend-race-game
 * Your custom SDK
 *
 * The version of the OpenAPI document: lap-legend-race-game: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StorageBatchSingleIncrementCounterResponse } from './StorageBatchSingleIncrementCounterResponse';
import {
    StorageBatchSingleIncrementCounterResponseFromJSON,
    StorageBatchSingleIncrementCounterResponseFromJSONTyped,
    StorageBatchSingleIncrementCounterResponseToJSON,
} from './StorageBatchSingleIncrementCounterResponse';

/**
 * 
 * @export
 * @interface StorageBatchIncrementCounterResponse
 */
export interface StorageBatchIncrementCounterResponse {
    /**
     * 
     * @type {Array<StorageBatchSingleIncrementCounterResponse>}
     * @memberof StorageBatchIncrementCounterResponse
     */
    counters?: Array<StorageBatchSingleIncrementCounterResponse>;
}

/**
 * Check if a given object implements the StorageBatchIncrementCounterResponse interface.
 */
export function instanceOfStorageBatchIncrementCounterResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StorageBatchIncrementCounterResponseFromJSON(json: any): StorageBatchIncrementCounterResponse {
    return StorageBatchIncrementCounterResponseFromJSONTyped(json, false);
}

export function StorageBatchIncrementCounterResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageBatchIncrementCounterResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'counters': !exists(json, 'counters') ? undefined : ((json['counters'] as Array<any>).map(StorageBatchSingleIncrementCounterResponseFromJSON)),
    };
}

export function StorageBatchIncrementCounterResponseToJSON(value?: StorageBatchIncrementCounterResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'counters': value.counters === undefined ? undefined : ((value.counters as Array<any>).map(StorageBatchSingleIncrementCounterResponseToJSON)),
    };
}

