/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v6 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StorageBatchGetBlobsSingleResponse } from './StorageBatchGetBlobsSingleResponse';
import {
    StorageBatchGetBlobsSingleResponseFromJSON,
    StorageBatchGetBlobsSingleResponseFromJSONTyped,
    StorageBatchGetBlobsSingleResponseToJSON,
} from './StorageBatchGetBlobsSingleResponse';
import type { StorageUserBlobResponse } from './StorageUserBlobResponse';
import {
    StorageUserBlobResponseFromJSON,
    StorageUserBlobResponseFromJSONTyped,
    StorageUserBlobResponseToJSON,
} from './StorageUserBlobResponse';

/**
 * 
 * @export
 * @interface StorageBatchGetBlobsResponse
 */
export interface StorageBatchGetBlobsResponse {
    /**
     * 
     * @type {Array<StorageUserBlobResponse>}
     * @memberof StorageBatchGetBlobsResponse
     */
    blobs?: Array<StorageUserBlobResponse>;
    /**
     * 
     * @type {Array<StorageBatchGetBlobsSingleResponse>}
     * @memberof StorageBatchGetBlobsResponse
     */
    results?: Array<StorageBatchGetBlobsSingleResponse>;
}

/**
 * Check if a given object implements the StorageBatchGetBlobsResponse interface.
 */
export function instanceOfStorageBatchGetBlobsResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StorageBatchGetBlobsResponseFromJSON(json: any): StorageBatchGetBlobsResponse {
    return StorageBatchGetBlobsResponseFromJSONTyped(json, false);
}

export function StorageBatchGetBlobsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageBatchGetBlobsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'blobs': !exists(json, 'blobs') ? undefined : ((json['blobs'] as Array<any>).map(StorageUserBlobResponseFromJSON)),
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(StorageBatchGetBlobsSingleResponseFromJSON)),
    };
}

export function StorageBatchGetBlobsResponseToJSON(value?: StorageBatchGetBlobsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'blobs': value.blobs === undefined ? undefined : ((value.blobs as Array<any>).map(StorageUserBlobResponseToJSON)),
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(StorageBatchGetBlobsSingleResponseToJSON)),
    };
}

