/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v6 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StorageInsertJsonBlobResponse
 */
export interface StorageInsertJsonBlobResponse {
    /**
     * CAS value used for future operations
     * @type {string}
     * @memberof StorageInsertJsonBlobResponse
     */
    cas?: string;
}

/**
 * Check if a given object implements the StorageInsertJsonBlobResponse interface.
 */
export function instanceOfStorageInsertJsonBlobResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StorageInsertJsonBlobResponseFromJSON(json: any): StorageInsertJsonBlobResponse {
    return StorageInsertJsonBlobResponseFromJSONTyped(json, false);
}

export function StorageInsertJsonBlobResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageInsertJsonBlobResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cas': !exists(json, 'cas') ? undefined : json['cas'],
    };
}

export function StorageInsertJsonBlobResponseToJSON(value?: StorageInsertJsonBlobResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cas': value.cas,
    };
}

