/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v6 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StorageGetSubDocumentRequest } from './StorageGetSubDocumentRequest';
import {
    StorageGetSubDocumentRequestFromJSON,
    StorageGetSubDocumentRequestFromJSONTyped,
    StorageGetSubDocumentRequestToJSON,
} from './StorageGetSubDocumentRequest';
import type { StorageGetSubDocumentResponse } from './StorageGetSubDocumentResponse';
import {
    StorageGetSubDocumentResponseFromJSON,
    StorageGetSubDocumentResponseFromJSONTyped,
    StorageGetSubDocumentResponseToJSON,
} from './StorageGetSubDocumentResponse';

/**
 * 
 * @export
 * @interface StorageBatchGetSubDocumentsSingleResponse
 */
export interface StorageBatchGetSubDocumentsSingleResponse {
    /**
     * 
     * @type {string}
     * @memberof StorageBatchGetSubDocumentsSingleResponse
     */
    message?: string;
    /**
     * 
     * @type {StorageGetSubDocumentRequest}
     * @memberof StorageBatchGetSubDocumentsSingleResponse
     */
    request?: StorageGetSubDocumentRequest;
    /**
     * 
     * @type {StorageGetSubDocumentResponse}
     * @memberof StorageBatchGetSubDocumentsSingleResponse
     */
    response?: StorageGetSubDocumentResponse;
    /**
     * 
     * @type {boolean}
     * @memberof StorageBatchGetSubDocumentsSingleResponse
     */
    success?: boolean;
}

/**
 * Check if a given object implements the StorageBatchGetSubDocumentsSingleResponse interface.
 */
export function instanceOfStorageBatchGetSubDocumentsSingleResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StorageBatchGetSubDocumentsSingleResponseFromJSON(json: any): StorageBatchGetSubDocumentsSingleResponse {
    return StorageBatchGetSubDocumentsSingleResponseFromJSONTyped(json, false);
}

export function StorageBatchGetSubDocumentsSingleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageBatchGetSubDocumentsSingleResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
        'request': !exists(json, 'request') ? undefined : StorageGetSubDocumentRequestFromJSON(json['request']),
        'response': !exists(json, 'response') ? undefined : StorageGetSubDocumentResponseFromJSON(json['response']),
        'success': !exists(json, 'success') ? undefined : json['success'],
    };
}

export function StorageBatchGetSubDocumentsSingleResponseToJSON(value?: StorageBatchGetSubDocumentsSingleResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'request': StorageGetSubDocumentRequestToJSON(value.request),
        'response': StorageGetSubDocumentResponseToJSON(value.response),
        'success': value.success,
    };
}

