/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v6 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StorageBatchGetSubDocumentsSingleResponse } from './StorageBatchGetSubDocumentsSingleResponse';
import {
    StorageBatchGetSubDocumentsSingleResponseFromJSON,
    StorageBatchGetSubDocumentsSingleResponseFromJSONTyped,
    StorageBatchGetSubDocumentsSingleResponseToJSON,
} from './StorageBatchGetSubDocumentsSingleResponse';

/**
 * 
 * @export
 * @interface StorageBatchGetSubDocumentsResponse
 */
export interface StorageBatchGetSubDocumentsResponse {
    /**
     * 
     * @type {Array<StorageBatchGetSubDocumentsSingleResponse>}
     * @memberof StorageBatchGetSubDocumentsResponse
     */
    results?: Array<StorageBatchGetSubDocumentsSingleResponse>;
}

/**
 * Check if a given object implements the StorageBatchGetSubDocumentsResponse interface.
 */
export function instanceOfStorageBatchGetSubDocumentsResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StorageBatchGetSubDocumentsResponseFromJSON(json: any): StorageBatchGetSubDocumentsResponse {
    return StorageBatchGetSubDocumentsResponseFromJSONTyped(json, false);
}

export function StorageBatchGetSubDocumentsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageBatchGetSubDocumentsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(StorageBatchGetSubDocumentsSingleResponseFromJSON)),
    };
}

export function StorageBatchGetSubDocumentsResponseToJSON(value?: StorageBatchGetSubDocumentsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(StorageBatchGetSubDocumentsSingleResponseToJSON)),
    };
}

