/* tslint:disable */
/* eslint-disable */
/**
 * lap-legend-race-game
 * Your custom SDK
 *
 * The version of the OpenAPI document: lap-legend-race-game: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StorageServiceUpdateAppendBlobBody
 */
export interface StorageServiceUpdateAppendBlobBody {
    /**
     * Value to be appended
     * @type {string}
     * @memberof StorageServiceUpdateAppendBlobBody
     */
    value: string;
}

/**
 * Check if a given object implements the StorageServiceUpdateAppendBlobBody interface.
 */
export function instanceOfStorageServiceUpdateAppendBlobBody(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function StorageServiceUpdateAppendBlobBodyFromJSON(json: any): StorageServiceUpdateAppendBlobBody {
    return StorageServiceUpdateAppendBlobBodyFromJSONTyped(json, false);
}

export function StorageServiceUpdateAppendBlobBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageServiceUpdateAppendBlobBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': json['value'],
    };
}

export function StorageServiceUpdateAppendBlobBodyToJSON(value?: StorageServiceUpdateAppendBlobBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
    };
}

