/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v6 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StorageBatchGetJsonBlobsSingleResponse } from './StorageBatchGetJsonBlobsSingleResponse';
import {
    StorageBatchGetJsonBlobsSingleResponseFromJSON,
    StorageBatchGetJsonBlobsSingleResponseFromJSONTyped,
    StorageBatchGetJsonBlobsSingleResponseToJSON,
} from './StorageBatchGetJsonBlobsSingleResponse';

/**
 * 
 * @export
 * @interface StorageBatchGetJsonBlobsResponse
 */
export interface StorageBatchGetJsonBlobsResponse {
    /**
     * 
     * @type {Array<StorageBatchGetJsonBlobsSingleResponse>}
     * @memberof StorageBatchGetJsonBlobsResponse
     */
    results?: Array<StorageBatchGetJsonBlobsSingleResponse>;
}

/**
 * Check if a given object implements the StorageBatchGetJsonBlobsResponse interface.
 */
export function instanceOfStorageBatchGetJsonBlobsResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StorageBatchGetJsonBlobsResponseFromJSON(json: any): StorageBatchGetJsonBlobsResponse {
    return StorageBatchGetJsonBlobsResponseFromJSONTyped(json, false);
}

export function StorageBatchGetJsonBlobsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageBatchGetJsonBlobsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(StorageBatchGetJsonBlobsSingleResponseFromJSON)),
    };
}

export function StorageBatchGetJsonBlobsResponseToJSON(value?: StorageBatchGetJsonBlobsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(StorageBatchGetJsonBlobsSingleResponseToJSON)),
    };
}

