/* tslint:disable */
/* eslint-disable */
/**
 * test
 * Your custom SDK
 *
 * The version of the OpenAPI document: test: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StorageDeleteJsonBlobRequest
 */
export interface StorageDeleteJsonBlobRequest {
    /**
     * Access to the blob. (public/protected/private)
     * @type {string}
     * @memberof StorageDeleteJsonBlobRequest
     */
    accessType: StorageDeleteJsonBlobRequestAccessTypeEnum;
    /**
     * Optional CAS value retrieved from the last operation. CAS mismatch will be ignored if not passed
     * @type {string}
     * @memberof StorageDeleteJsonBlobRequest
     */
    cas?: string;
    /**
     * Blob key
     * @type {string}
     * @memberof StorageDeleteJsonBlobRequest
     */
    jsonBlobKey: string;
    /**
     * Blob owner's user ID
     * @type {string}
     * @memberof StorageDeleteJsonBlobRequest
     */
    ownerId: string;
}


/**
 * @export
 */
export const StorageDeleteJsonBlobRequestAccessTypeEnum = {
    Public: 'public',
    Private: 'private',
    Protected: 'protected'
} as const;
export type StorageDeleteJsonBlobRequestAccessTypeEnum = typeof StorageDeleteJsonBlobRequestAccessTypeEnum[keyof typeof StorageDeleteJsonBlobRequestAccessTypeEnum];


/**
 * Check if a given object implements the StorageDeleteJsonBlobRequest interface.
 */
export function instanceOfStorageDeleteJsonBlobRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "accessType" in value;
    isInstance = isInstance && "jsonBlobKey" in value;
    isInstance = isInstance && "ownerId" in value;

    return isInstance;
}

export function StorageDeleteJsonBlobRequestFromJSON(json: any): StorageDeleteJsonBlobRequest {
    return StorageDeleteJsonBlobRequestFromJSONTyped(json, false);
}

export function StorageDeleteJsonBlobRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageDeleteJsonBlobRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessType': json['access_type'],
        'cas': !exists(json, 'cas') ? undefined : json['cas'],
        'jsonBlobKey': json['json_blob_key'],
        'ownerId': json['owner_id'],
    };
}

export function StorageDeleteJsonBlobRequestToJSON(value?: StorageDeleteJsonBlobRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'access_type': value.accessType,
        'cas': value.cas,
        'json_blob_key': value.jsonBlobKey,
        'owner_id': value.ownerId,
    };
}

