/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v6 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StorageInsertBlobRequest } from './StorageInsertBlobRequest';
import {
    StorageInsertBlobRequestFromJSON,
    StorageInsertBlobRequestFromJSONTyped,
    StorageInsertBlobRequestToJSON,
} from './StorageInsertBlobRequest';

/**
 * 
 * @export
 * @interface StorageBatchInsertBlobRequest
 */
export interface StorageBatchInsertBlobRequest {
    /**
     * 
     * @type {Array<StorageInsertBlobRequest>}
     * @memberof StorageBatchInsertBlobRequest
     */
    blobs?: Array<StorageInsertBlobRequest>;
}

/**
 * Check if a given object implements the StorageBatchInsertBlobRequest interface.
 */
export function instanceOfStorageBatchInsertBlobRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StorageBatchInsertBlobRequestFromJSON(json: any): StorageBatchInsertBlobRequest {
    return StorageBatchInsertBlobRequestFromJSONTyped(json, false);
}

export function StorageBatchInsertBlobRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageBatchInsertBlobRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'blobs': !exists(json, 'blobs') ? undefined : ((json['blobs'] as Array<any>).map(StorageInsertBlobRequestFromJSON)),
    };
}

export function StorageBatchInsertBlobRequestToJSON(value?: StorageBatchInsertBlobRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'blobs': value.blobs === undefined ? undefined : ((value.blobs as Array<any>).map(StorageInsertBlobRequestToJSON)),
    };
}

