/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v6 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StoragePrependArrSubDocumentRequest } from './StoragePrependArrSubDocumentRequest';
import {
    StoragePrependArrSubDocumentRequestFromJSON,
    StoragePrependArrSubDocumentRequestFromJSONTyped,
    StoragePrependArrSubDocumentRequestToJSON,
} from './StoragePrependArrSubDocumentRequest';
import type { StoragePrependArrSubDocumentResponse } from './StoragePrependArrSubDocumentResponse';
import {
    StoragePrependArrSubDocumentResponseFromJSON,
    StoragePrependArrSubDocumentResponseFromJSONTyped,
    StoragePrependArrSubDocumentResponseToJSON,
} from './StoragePrependArrSubDocumentResponse';

/**
 * 
 * @export
 * @interface StorageBatchPrependArrSubDocumentSingleResponse
 */
export interface StorageBatchPrependArrSubDocumentSingleResponse {
    /**
     * 
     * @type {string}
     * @memberof StorageBatchPrependArrSubDocumentSingleResponse
     */
    message?: string;
    /**
     * 
     * @type {StoragePrependArrSubDocumentRequest}
     * @memberof StorageBatchPrependArrSubDocumentSingleResponse
     */
    request?: StoragePrependArrSubDocumentRequest;
    /**
     * 
     * @type {StoragePrependArrSubDocumentResponse}
     * @memberof StorageBatchPrependArrSubDocumentSingleResponse
     */
    response?: StoragePrependArrSubDocumentResponse;
    /**
     * 
     * @type {boolean}
     * @memberof StorageBatchPrependArrSubDocumentSingleResponse
     */
    success?: boolean;
}

/**
 * Check if a given object implements the StorageBatchPrependArrSubDocumentSingleResponse interface.
 */
export function instanceOfStorageBatchPrependArrSubDocumentSingleResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StorageBatchPrependArrSubDocumentSingleResponseFromJSON(json: any): StorageBatchPrependArrSubDocumentSingleResponse {
    return StorageBatchPrependArrSubDocumentSingleResponseFromJSONTyped(json, false);
}

export function StorageBatchPrependArrSubDocumentSingleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageBatchPrependArrSubDocumentSingleResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
        'request': !exists(json, 'request') ? undefined : StoragePrependArrSubDocumentRequestFromJSON(json['request']),
        'response': !exists(json, 'response') ? undefined : StoragePrependArrSubDocumentResponseFromJSON(json['response']),
        'success': !exists(json, 'success') ? undefined : json['success'],
    };
}

export function StorageBatchPrependArrSubDocumentSingleResponseToJSON(value?: StorageBatchPrependArrSubDocumentSingleResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'request': StoragePrependArrSubDocumentRequestToJSON(value.request),
        'response': StoragePrependArrSubDocumentResponseToJSON(value.response),
        'success': value.success,
    };
}

