/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v6 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StorageUserBlobResponse
 */
export interface StorageUserBlobResponse {
    /**
     * CAS value used for future operations
     * @type {string}
     * @memberof StorageUserBlobResponse
     */
    cas?: string;
    /**
     * Blob owner's user ID
     * @type {string}
     * @memberof StorageUserBlobResponse
     */
    ownerId?: string;
    /**
     * Blob value
     * @type {string}
     * @memberof StorageUserBlobResponse
     */
    value?: string;
}

/**
 * Check if a given object implements the StorageUserBlobResponse interface.
 */
export function instanceOfStorageUserBlobResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StorageUserBlobResponseFromJSON(json: any): StorageUserBlobResponse {
    return StorageUserBlobResponseFromJSONTyped(json, false);
}

export function StorageUserBlobResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageUserBlobResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cas': !exists(json, 'cas') ? undefined : json['cas'],
        'ownerId': !exists(json, 'owner_id') ? undefined : json['owner_id'],
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function StorageUserBlobResponseToJSON(value?: StorageUserBlobResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cas': value.cas,
        'owner_id': value.ownerId,
        'value': value.value,
    };
}

