/* tslint:disable */
/* eslint-disable */
/**
 * lap-legend-race-game
 * Your custom SDK
 *
 * The version of the OpenAPI document: lap-legend-race-game: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StorageUserAppendBlobResponse
 */
export interface StorageUserAppendBlobResponse {
    /**
     * CAS value used for future operations
     * @type {string}
     * @memberof StorageUserAppendBlobResponse
     */
    cas?: string;
    /**
     * Append-blob owner's user ID
     * @type {string}
     * @memberof StorageUserAppendBlobResponse
     */
    ownerId?: string;
    /**
     * Append-blob value
     * @type {string}
     * @memberof StorageUserAppendBlobResponse
     */
    value?: string;
}

/**
 * Check if a given object implements the StorageUserAppendBlobResponse interface.
 */
export function instanceOfStorageUserAppendBlobResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StorageUserAppendBlobResponseFromJSON(json: any): StorageUserAppendBlobResponse {
    return StorageUserAppendBlobResponseFromJSONTyped(json, false);
}

export function StorageUserAppendBlobResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageUserAppendBlobResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cas': !exists(json, 'cas') ? undefined : json['cas'],
        'ownerId': !exists(json, 'owner_id') ? undefined : json['owner_id'],
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function StorageUserAppendBlobResponseToJSON(value?: StorageUserAppendBlobResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cas': value.cas,
        'owner_id': value.ownerId,
        'value': value.value,
    };
}

