/* tslint:disable */
/* eslint-disable */
/**
 * test
 * Your custom SDK
 *
 * The version of the OpenAPI document: test: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StorageInsertJsonBlobRequest
 */
export interface StorageInsertJsonBlobRequest {
    /**
     * Access to the blob. (public/protected/private)
     * @type {string}
     * @memberof StorageInsertJsonBlobRequest
     */
    accessType: StorageInsertJsonBlobRequestAccessTypeEnum;
    /**
     * Blob key
     * @type {string}
     * @memberof StorageInsertJsonBlobRequest
     */
    jsonBlobKey: string;
    /**
     * Blob owner's user ID
     * @type {string}
     * @memberof StorageInsertJsonBlobRequest
     */
    ownerId: string;
    /**
     * Optional TTL for the blob
     * @type {number}
     * @memberof StorageInsertJsonBlobRequest
     */
    ttl?: number;
    /**
     * JSON value to be inserted
     * @type {object}
     * @memberof StorageInsertJsonBlobRequest
     */
    value: object;
}


/**
 * @export
 */
export const StorageInsertJsonBlobRequestAccessTypeEnum = {
    Public: 'public',
    Private: 'private',
    Protected: 'protected'
} as const;
export type StorageInsertJsonBlobRequestAccessTypeEnum = typeof StorageInsertJsonBlobRequestAccessTypeEnum[keyof typeof StorageInsertJsonBlobRequestAccessTypeEnum];


/**
 * Check if a given object implements the StorageInsertJsonBlobRequest interface.
 */
export function instanceOfStorageInsertJsonBlobRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "accessType" in value;
    isInstance = isInstance && "jsonBlobKey" in value;
    isInstance = isInstance && "ownerId" in value;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function StorageInsertJsonBlobRequestFromJSON(json: any): StorageInsertJsonBlobRequest {
    return StorageInsertJsonBlobRequestFromJSONTyped(json, false);
}

export function StorageInsertJsonBlobRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageInsertJsonBlobRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessType': json['access_type'],
        'jsonBlobKey': json['json_blob_key'],
        'ownerId': json['owner_id'],
        'ttl': !exists(json, 'ttl') ? undefined : json['ttl'],
        'value': json['value'],
    };
}

export function StorageInsertJsonBlobRequestToJSON(value?: StorageInsertJsonBlobRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'access_type': value.accessType,
        'json_blob_key': value.jsonBlobKey,
        'owner_id': value.ownerId,
        'ttl': value.ttl,
        'value': value.value,
    };
}

