/* tslint:disable */
/* eslint-disable */
/**
 * lap-legend-race-game
 * Your custom SDK
 *
 * The version of the OpenAPI document: lap-legend-race-game: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StorageBatchUpsertSubDocumentSingleResponse } from './StorageBatchUpsertSubDocumentSingleResponse';
import {
    StorageBatchUpsertSubDocumentSingleResponseFromJSON,
    StorageBatchUpsertSubDocumentSingleResponseFromJSONTyped,
    StorageBatchUpsertSubDocumentSingleResponseToJSON,
} from './StorageBatchUpsertSubDocumentSingleResponse';

/**
 * 
 * @export
 * @interface StorageBatchUpsertSubDocumentsResponse
 */
export interface StorageBatchUpsertSubDocumentsResponse {
    /**
     * 
     * @type {Array<StorageBatchUpsertSubDocumentSingleResponse>}
     * @memberof StorageBatchUpsertSubDocumentsResponse
     */
    results?: Array<StorageBatchUpsertSubDocumentSingleResponse>;
}

/**
 * Check if a given object implements the StorageBatchUpsertSubDocumentsResponse interface.
 */
export function instanceOfStorageBatchUpsertSubDocumentsResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StorageBatchUpsertSubDocumentsResponseFromJSON(json: any): StorageBatchUpsertSubDocumentsResponse {
    return StorageBatchUpsertSubDocumentsResponseFromJSONTyped(json, false);
}

export function StorageBatchUpsertSubDocumentsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageBatchUpsertSubDocumentsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(StorageBatchUpsertSubDocumentSingleResponseFromJSON)),
    };
}

export function StorageBatchUpsertSubDocumentsResponseToJSON(value?: StorageBatchUpsertSubDocumentsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(StorageBatchUpsertSubDocumentSingleResponseToJSON)),
    };
}

