/* tslint:disable */
/* eslint-disable */
/**
 * lap-legend-race-game
 * Your custom SDK
 *
 * The version of the OpenAPI document: lap-legend-race-game: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StorageGetBlobRequest
 */
export interface StorageGetBlobRequest {
    /**
     * Access to the blob. (public/protected/private)
     * @type {string}
     * @memberof StorageGetBlobRequest
     */
    accessType: StorageGetBlobRequestAccessTypeEnum;
    /**
     * Blob key
     * @type {string}
     * @memberof StorageGetBlobRequest
     */
    blobKey: string;
    /**
     * Blob owner's user ID
     * @type {string}
     * @memberof StorageGetBlobRequest
     */
    ownerId: string;
}


/**
 * @export
 */
export const StorageGetBlobRequestAccessTypeEnum = {
    Public: 'public',
    Private: 'private',
    Protected: 'protected'
} as const;
export type StorageGetBlobRequestAccessTypeEnum = typeof StorageGetBlobRequestAccessTypeEnum[keyof typeof StorageGetBlobRequestAccessTypeEnum];


/**
 * Check if a given object implements the StorageGetBlobRequest interface.
 */
export function instanceOfStorageGetBlobRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "accessType" in value;
    isInstance = isInstance && "blobKey" in value;
    isInstance = isInstance && "ownerId" in value;

    return isInstance;
}

export function StorageGetBlobRequestFromJSON(json: any): StorageGetBlobRequest {
    return StorageGetBlobRequestFromJSONTyped(json, false);
}

export function StorageGetBlobRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageGetBlobRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessType': json['access_type'],
        'blobKey': json['blob_key'],
        'ownerId': json['owner_id'],
    };
}

export function StorageGetBlobRequestToJSON(value?: StorageGetBlobRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'access_type': value.accessType,
        'blob_key': value.blobKey,
        'owner_id': value.ownerId,
    };
}

