/* tslint:disable */
/* eslint-disable */
/**
 * lap-legend-race-game
 * Your custom SDK
 *
 * The version of the OpenAPI document: lap-legend-race-game: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StorageReplaceBlobRequest } from './StorageReplaceBlobRequest';
import {
    StorageReplaceBlobRequestFromJSON,
    StorageReplaceBlobRequestFromJSONTyped,
    StorageReplaceBlobRequestToJSON,
} from './StorageReplaceBlobRequest';

/**
 * 
 * @export
 * @interface StorageBatchReplaceBlobRequest
 */
export interface StorageBatchReplaceBlobRequest {
    /**
     * 
     * @type {Array<StorageReplaceBlobRequest>}
     * @memberof StorageBatchReplaceBlobRequest
     */
    blobs?: Array<StorageReplaceBlobRequest>;
}

/**
 * Check if a given object implements the StorageBatchReplaceBlobRequest interface.
 */
export function instanceOfStorageBatchReplaceBlobRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StorageBatchReplaceBlobRequestFromJSON(json: any): StorageBatchReplaceBlobRequest {
    return StorageBatchReplaceBlobRequestFromJSONTyped(json, false);
}

export function StorageBatchReplaceBlobRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageBatchReplaceBlobRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'blobs': !exists(json, 'blobs') ? undefined : ((json['blobs'] as Array<any>).map(StorageReplaceBlobRequestFromJSON)),
    };
}

export function StorageBatchReplaceBlobRequestToJSON(value?: StorageBatchReplaceBlobRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'blobs': value.blobs === undefined ? undefined : ((value.blobs as Array<any>).map(StorageReplaceBlobRequestToJSON)),
    };
}

