/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v6 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StorageGetAppendBlobResponse
 */
export interface StorageGetAppendBlobResponse {
    /**
     * CAS value used for future operations
     * @type {string}
     * @memberof StorageGetAppendBlobResponse
     */
    cas?: string;
    /**
     * Blob value
     * @type {string}
     * @memberof StorageGetAppendBlobResponse
     */
    value?: string;
}

/**
 * Check if a given object implements the StorageGetAppendBlobResponse interface.
 */
export function instanceOfStorageGetAppendBlobResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StorageGetAppendBlobResponseFromJSON(json: any): StorageGetAppendBlobResponse {
    return StorageGetAppendBlobResponseFromJSONTyped(json, false);
}

export function StorageGetAppendBlobResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageGetAppendBlobResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cas': !exists(json, 'cas') ? undefined : json['cas'],
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function StorageGetAppendBlobResponseToJSON(value?: StorageGetAppendBlobResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cas': value.cas,
        'value': value.value,
    };
}

