/* tslint:disable */
/* eslint-disable */
/**
 * lap-legend-race-game
 * Your custom SDK
 *
 * The version of the OpenAPI document: lap-legend-race-game: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StorageReplaceJsonBlobResponse
 */
export interface StorageReplaceJsonBlobResponse {
    /**
     * CAS value used for future operations
     * @type {string}
     * @memberof StorageReplaceJsonBlobResponse
     */
    cas?: string;
}

/**
 * Check if a given object implements the StorageReplaceJsonBlobResponse interface.
 */
export function instanceOfStorageReplaceJsonBlobResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StorageReplaceJsonBlobResponseFromJSON(json: any): StorageReplaceJsonBlobResponse {
    return StorageReplaceJsonBlobResponseFromJSONTyped(json, false);
}

export function StorageReplaceJsonBlobResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageReplaceJsonBlobResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cas': !exists(json, 'cas') ? undefined : json['cas'],
    };
}

export function StorageReplaceJsonBlobResponseToJSON(value?: StorageReplaceJsonBlobResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cas': value.cas,
    };
}

