/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v6 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StorageReplaceJsonBlobRequest
 */
export interface StorageReplaceJsonBlobRequest {
    /**
     * Access to the blob. (public/protected/private)
     * @type {string}
     * @memberof StorageReplaceJsonBlobRequest
     */
    accessType: StorageReplaceJsonBlobRequestAccessTypeEnum;
    /**
     * CAS value retrieved from the last operation
     * @type {string}
     * @memberof StorageReplaceJsonBlobRequest
     */
    cas?: string;
    /**
     * Whether the json blob should be created if it doesn't exist
     * @type {boolean}
     * @memberof StorageReplaceJsonBlobRequest
     */
    create?: boolean;
    /**
     * Blob key
     * @type {string}
     * @memberof StorageReplaceJsonBlobRequest
     */
    jsonBlobKey: string;
    /**
     * Blob owner's user ID
     * @type {string}
     * @memberof StorageReplaceJsonBlobRequest
     */
    ownerId: string;
    /**
     * Optional TTL for the json blob
     * @type {number}
     * @memberof StorageReplaceJsonBlobRequest
     */
    ttl?: number;
    /**
     * JSON value to be inserted
     * @type {object}
     * @memberof StorageReplaceJsonBlobRequest
     */
    value: object;
}


/**
 * @export
 */
export const StorageReplaceJsonBlobRequestAccessTypeEnum = {
    Public: 'public',
    Private: 'private',
    Protected: 'protected'
} as const;
export type StorageReplaceJsonBlobRequestAccessTypeEnum = typeof StorageReplaceJsonBlobRequestAccessTypeEnum[keyof typeof StorageReplaceJsonBlobRequestAccessTypeEnum];


/**
 * Check if a given object implements the StorageReplaceJsonBlobRequest interface.
 */
export function instanceOfStorageReplaceJsonBlobRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "accessType" in value;
    isInstance = isInstance && "jsonBlobKey" in value;
    isInstance = isInstance && "ownerId" in value;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function StorageReplaceJsonBlobRequestFromJSON(json: any): StorageReplaceJsonBlobRequest {
    return StorageReplaceJsonBlobRequestFromJSONTyped(json, false);
}

export function StorageReplaceJsonBlobRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageReplaceJsonBlobRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessType': json['access_type'],
        'cas': !exists(json, 'cas') ? undefined : json['cas'],
        'create': !exists(json, 'create') ? undefined : json['create'],
        'jsonBlobKey': json['json_blob_key'],
        'ownerId': json['owner_id'],
        'ttl': !exists(json, 'ttl') ? undefined : json['ttl'],
        'value': json['value'],
    };
}

export function StorageReplaceJsonBlobRequestToJSON(value?: StorageReplaceJsonBlobRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'access_type': value.accessType,
        'cas': value.cas,
        'create': value.create,
        'json_blob_key': value.jsonBlobKey,
        'owner_id': value.ownerId,
        'ttl': value.ttl,
        'value': value.value,
    };
}

