/* tslint:disable */
/* eslint-disable */
/**
 * lap-legend-race-game
 * Your custom SDK
 *
 * The version of the OpenAPI document: lap-legend-race-game: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StorageBatchAppendArrSubDocumentSingleResponse } from './StorageBatchAppendArrSubDocumentSingleResponse';
import {
    StorageBatchAppendArrSubDocumentSingleResponseFromJSON,
    StorageBatchAppendArrSubDocumentSingleResponseFromJSONTyped,
    StorageBatchAppendArrSubDocumentSingleResponseToJSON,
} from './StorageBatchAppendArrSubDocumentSingleResponse';

/**
 * 
 * @export
 * @interface StorageBatchAppendArrSubDocumentsResponse
 */
export interface StorageBatchAppendArrSubDocumentsResponse {
    /**
     * 
     * @type {Array<StorageBatchAppendArrSubDocumentSingleResponse>}
     * @memberof StorageBatchAppendArrSubDocumentsResponse
     */
    results?: Array<StorageBatchAppendArrSubDocumentSingleResponse>;
}

/**
 * Check if a given object implements the StorageBatchAppendArrSubDocumentsResponse interface.
 */
export function instanceOfStorageBatchAppendArrSubDocumentsResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StorageBatchAppendArrSubDocumentsResponseFromJSON(json: any): StorageBatchAppendArrSubDocumentsResponse {
    return StorageBatchAppendArrSubDocumentsResponseFromJSONTyped(json, false);
}

export function StorageBatchAppendArrSubDocumentsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageBatchAppendArrSubDocumentsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(StorageBatchAppendArrSubDocumentSingleResponseFromJSON)),
    };
}

export function StorageBatchAppendArrSubDocumentsResponseToJSON(value?: StorageBatchAppendArrSubDocumentsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(StorageBatchAppendArrSubDocumentSingleResponseToJSON)),
    };
}

