/* tslint:disable */
/* eslint-disable */
/**
 * lap-legend-race-game
 * Your custom SDK
 *
 * The version of the OpenAPI document: lap-legend-race-game: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StorageUpdateAppendBlobRequest } from './StorageUpdateAppendBlobRequest';
import {
    StorageUpdateAppendBlobRequestFromJSON,
    StorageUpdateAppendBlobRequestFromJSONTyped,
    StorageUpdateAppendBlobRequestToJSON,
} from './StorageUpdateAppendBlobRequest';

/**
 * 
 * @export
 * @interface StorageBatchUpdateAppendBlobRequest
 */
export interface StorageBatchUpdateAppendBlobRequest {
    /**
     * 
     * @type {Array<StorageUpdateAppendBlobRequest>}
     * @memberof StorageBatchUpdateAppendBlobRequest
     */
    appendBlobs?: Array<StorageUpdateAppendBlobRequest>;
}

/**
 * Check if a given object implements the StorageBatchUpdateAppendBlobRequest interface.
 */
export function instanceOfStorageBatchUpdateAppendBlobRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StorageBatchUpdateAppendBlobRequestFromJSON(json: any): StorageBatchUpdateAppendBlobRequest {
    return StorageBatchUpdateAppendBlobRequestFromJSONTyped(json, false);
}

export function StorageBatchUpdateAppendBlobRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageBatchUpdateAppendBlobRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'appendBlobs': !exists(json, 'appendBlobs') ? undefined : ((json['appendBlobs'] as Array<any>).map(StorageUpdateAppendBlobRequestFromJSON)),
    };
}

export function StorageBatchUpdateAppendBlobRequestToJSON(value?: StorageBatchUpdateAppendBlobRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'appendBlobs': value.appendBlobs === undefined ? undefined : ((value.appendBlobs as Array<any>).map(StorageUpdateAppendBlobRequestToJSON)),
    };
}

