/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v6 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StorageAppendArrSubDocumentResponse
 */
export interface StorageAppendArrSubDocumentResponse {
    /**
     * CAS value used for future operations
     * @type {string}
     * @memberof StorageAppendArrSubDocumentResponse
     */
    cas?: string;
}

/**
 * Check if a given object implements the StorageAppendArrSubDocumentResponse interface.
 */
export function instanceOfStorageAppendArrSubDocumentResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StorageAppendArrSubDocumentResponseFromJSON(json: any): StorageAppendArrSubDocumentResponse {
    return StorageAppendArrSubDocumentResponseFromJSONTyped(json, false);
}

export function StorageAppendArrSubDocumentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageAppendArrSubDocumentResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cas': !exists(json, 'cas') ? undefined : json['cas'],
    };
}

export function StorageAppendArrSubDocumentResponseToJSON(value?: StorageAppendArrSubDocumentResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cas': value.cas,
    };
}

