/* tslint:disable */
/* eslint-disable */
/**
 * lap-legend-race-game
 * Your custom SDK
 *
 * The version of the OpenAPI document: lap-legend-race-game: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StorageDeleteSubDocumentRequest } from './StorageDeleteSubDocumentRequest';
import {
    StorageDeleteSubDocumentRequestFromJSON,
    StorageDeleteSubDocumentRequestFromJSONTyped,
    StorageDeleteSubDocumentRequestToJSON,
} from './StorageDeleteSubDocumentRequest';

/**
 * 
 * @export
 * @interface StorageBatchDeleteSubDocumentsRequest
 */
export interface StorageBatchDeleteSubDocumentsRequest {
    /**
     * 
     * @type {Array<StorageDeleteSubDocumentRequest>}
     * @memberof StorageBatchDeleteSubDocumentsRequest
     */
    subDocuments?: Array<StorageDeleteSubDocumentRequest>;
}

/**
 * Check if a given object implements the StorageBatchDeleteSubDocumentsRequest interface.
 */
export function instanceOfStorageBatchDeleteSubDocumentsRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StorageBatchDeleteSubDocumentsRequestFromJSON(json: any): StorageBatchDeleteSubDocumentsRequest {
    return StorageBatchDeleteSubDocumentsRequestFromJSONTyped(json, false);
}

export function StorageBatchDeleteSubDocumentsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageBatchDeleteSubDocumentsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'subDocuments': !exists(json, 'sub_documents') ? undefined : ((json['sub_documents'] as Array<any>).map(StorageDeleteSubDocumentRequestFromJSON)),
    };
}

export function StorageBatchDeleteSubDocumentsRequestToJSON(value?: StorageBatchDeleteSubDocumentsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sub_documents': value.subDocuments === undefined ? undefined : ((value.subDocuments as Array<any>).map(StorageDeleteSubDocumentRequestToJSON)),
    };
}

