/* tslint:disable */
/* eslint-disable */
/**
 * lap-legend-race-game
 * Your custom SDK
 *
 * The version of the OpenAPI document: lap-legend-race-game: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StorageUserCounterResponse
 */
export interface StorageUserCounterResponse {
    /**
     * Value of the counter
     * @type {number}
     * @memberof StorageUserCounterResponse
     */
    count: number;
    /**
     * Counter owner's user ID
     * @type {string}
     * @memberof StorageUserCounterResponse
     */
    ownerId?: string;
}

/**
 * Check if a given object implements the StorageUserCounterResponse interface.
 */
export function instanceOfStorageUserCounterResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "count" in value;

    return isInstance;
}

export function StorageUserCounterResponseFromJSON(json: any): StorageUserCounterResponse {
    return StorageUserCounterResponseFromJSONTyped(json, false);
}

export function StorageUserCounterResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageUserCounterResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': json['count'],
        'ownerId': !exists(json, 'owner_id') ? undefined : json['owner_id'],
    };
}

export function StorageUserCounterResponseToJSON(value?: StorageUserCounterResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'owner_id': value.ownerId,
    };
}

