/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v6 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StorageAppendBlobAndOwner } from './StorageAppendBlobAndOwner';
import {
    StorageAppendBlobAndOwnerFromJSON,
    StorageAppendBlobAndOwnerFromJSONTyped,
    StorageAppendBlobAndOwnerToJSON,
} from './StorageAppendBlobAndOwner';
import type { StorageUpdateAppendBlobRequest } from './StorageUpdateAppendBlobRequest';
import {
    StorageUpdateAppendBlobRequestFromJSON,
    StorageUpdateAppendBlobRequestFromJSONTyped,
    StorageUpdateAppendBlobRequestToJSON,
} from './StorageUpdateAppendBlobRequest';

/**
 * 
 * @export
 * @interface StorageBatchSingleUpdateAppendBlobResponse
 */
export interface StorageBatchSingleUpdateAppendBlobResponse {
    /**
     * 
     * @type {string}
     * @memberof StorageBatchSingleUpdateAppendBlobResponse
     */
    message?: string;
    /**
     * 
     * @type {StorageUpdateAppendBlobRequest}
     * @memberof StorageBatchSingleUpdateAppendBlobResponse
     */
    request?: StorageUpdateAppendBlobRequest;
    /**
     * 
     * @type {StorageAppendBlobAndOwner}
     * @memberof StorageBatchSingleUpdateAppendBlobResponse
     */
    response?: StorageAppendBlobAndOwner;
    /**
     * 
     * @type {boolean}
     * @memberof StorageBatchSingleUpdateAppendBlobResponse
     */
    success?: boolean;
}

/**
 * Check if a given object implements the StorageBatchSingleUpdateAppendBlobResponse interface.
 */
export function instanceOfStorageBatchSingleUpdateAppendBlobResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StorageBatchSingleUpdateAppendBlobResponseFromJSON(json: any): StorageBatchSingleUpdateAppendBlobResponse {
    return StorageBatchSingleUpdateAppendBlobResponseFromJSONTyped(json, false);
}

export function StorageBatchSingleUpdateAppendBlobResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageBatchSingleUpdateAppendBlobResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
        'request': !exists(json, 'request') ? undefined : StorageUpdateAppendBlobRequestFromJSON(json['request']),
        'response': !exists(json, 'response') ? undefined : StorageAppendBlobAndOwnerFromJSON(json['response']),
        'success': !exists(json, 'success') ? undefined : json['success'],
    };
}

export function StorageBatchSingleUpdateAppendBlobResponseToJSON(value?: StorageBatchSingleUpdateAppendBlobResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'request': StorageUpdateAppendBlobRequestToJSON(value.request),
        'response': StorageAppendBlobAndOwnerToJSON(value.response),
        'success': value.success,
    };
}

