/* tslint:disable */
/* eslint-disable */
/**
 * lap-legend-race-game
 * Your custom SDK
 *
 * The version of the OpenAPI document: lap-legend-race-game: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StorageJsonFragment
 */
export interface StorageJsonFragment {
    /**
     * 
     * @type {string}
     * @memberof StorageJsonFragment
     */
    path?: string;
    /**
     * 
     * @type {object}
     * @memberof StorageJsonFragment
     */
    value?: object;
}

/**
 * Check if a given object implements the StorageJsonFragment interface.
 */
export function instanceOfStorageJsonFragment(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StorageJsonFragmentFromJSON(json: any): StorageJsonFragment {
    return StorageJsonFragmentFromJSONTyped(json, false);
}

export function StorageJsonFragmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageJsonFragment {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'path': !exists(json, 'path') ? undefined : json['path'],
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function StorageJsonFragmentToJSON(value?: StorageJsonFragment | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'path': value.path,
        'value': value.value,
    };
}

