/* tslint:disable */
/* eslint-disable */
/**
 * lap-legend-race-game
 * Your custom SDK
 *
 * The version of the OpenAPI document: lap-legend-race-game: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StorageServiceReplaceBlobBody
 */
export interface StorageServiceReplaceBlobBody {
    /**
     * CAS value retrieved from the last operation
     * @type {string}
     * @memberof StorageServiceReplaceBlobBody
     */
    cas?: string;
    /**
     * Whether the blob should be created if it doesn't exist
     * @type {boolean}
     * @memberof StorageServiceReplaceBlobBody
     */
    create?: boolean;
    /**
     * Optional TTL for the blob
     * @type {number}
     * @memberof StorageServiceReplaceBlobBody
     */
    ttl?: number;
    /**
     * Blob value to be inserted
     * @type {string}
     * @memberof StorageServiceReplaceBlobBody
     */
    value: string;
}

/**
 * Check if a given object implements the StorageServiceReplaceBlobBody interface.
 */
export function instanceOfStorageServiceReplaceBlobBody(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function StorageServiceReplaceBlobBodyFromJSON(json: any): StorageServiceReplaceBlobBody {
    return StorageServiceReplaceBlobBodyFromJSONTyped(json, false);
}

export function StorageServiceReplaceBlobBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageServiceReplaceBlobBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cas': !exists(json, 'cas') ? undefined : json['cas'],
        'create': !exists(json, 'create') ? undefined : json['create'],
        'ttl': !exists(json, 'ttl') ? undefined : json['ttl'],
        'value': json['value'],
    };
}

export function StorageServiceReplaceBlobBodyToJSON(value?: StorageServiceReplaceBlobBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cas': value.cas,
        'create': value.create,
        'ttl': value.ttl,
        'value': value.value,
    };
}

