/* tslint:disable */
/* eslint-disable */
/**
 * lap-legend-race-game
 * Your custom SDK
 *
 * The version of the OpenAPI document: lap-legend-race-game: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StoragePrependArrSubDocumentRequest } from './StoragePrependArrSubDocumentRequest';
import {
    StoragePrependArrSubDocumentRequestFromJSON,
    StoragePrependArrSubDocumentRequestFromJSONTyped,
    StoragePrependArrSubDocumentRequestToJSON,
} from './StoragePrependArrSubDocumentRequest';

/**
 * 
 * @export
 * @interface StorageBatchPrependArrSubDocumentsRequest
 */
export interface StorageBatchPrependArrSubDocumentsRequest {
    /**
     * 
     * @type {Array<StoragePrependArrSubDocumentRequest>}
     * @memberof StorageBatchPrependArrSubDocumentsRequest
     */
    subDocuments?: Array<StoragePrependArrSubDocumentRequest>;
}

/**
 * Check if a given object implements the StorageBatchPrependArrSubDocumentsRequest interface.
 */
export function instanceOfStorageBatchPrependArrSubDocumentsRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StorageBatchPrependArrSubDocumentsRequestFromJSON(json: any): StorageBatchPrependArrSubDocumentsRequest {
    return StorageBatchPrependArrSubDocumentsRequestFromJSONTyped(json, false);
}

export function StorageBatchPrependArrSubDocumentsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageBatchPrependArrSubDocumentsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'subDocuments': !exists(json, 'sub_documents') ? undefined : ((json['sub_documents'] as Array<any>).map(StoragePrependArrSubDocumentRequestFromJSON)),
    };
}

export function StorageBatchPrependArrSubDocumentsRequestToJSON(value?: StorageBatchPrependArrSubDocumentsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sub_documents': value.subDocuments === undefined ? undefined : ((value.subDocuments as Array<any>).map(StoragePrependArrSubDocumentRequestToJSON)),
    };
}

