/* tslint:disable */
/* eslint-disable */
/**
 * test
 * Your custom SDK
 *
 * The version of the OpenAPI document: test: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StorageJsonFragment } from './StorageJsonFragment';
import {
    StorageJsonFragmentFromJSON,
    StorageJsonFragmentFromJSONTyped,
    StorageJsonFragmentToJSON,
} from './StorageJsonFragment';

/**
 * 
 * @export
 * @interface StorageAppendArrSubDocumentRequest
 */
export interface StorageAppendArrSubDocumentRequest {
    /**
     * Access to the counter. (public/protected/private)
     * @type {string}
     * @memberof StorageAppendArrSubDocumentRequest
     */
    accessType: StorageAppendArrSubDocumentRequestAccessTypeEnum;
    /**
     * Blob key
     * @type {string}
     * @memberof StorageAppendArrSubDocumentRequest
     */
    jsonBlobKey: string;
    /**
     * Counter owner's user ID
     * @type {string}
     * @memberof StorageAppendArrSubDocumentRequest
     */
    ownerId: string;
    /**
     * Fragments to be appended
     * @type {Array<StorageJsonFragment>}
     * @memberof StorageAppendArrSubDocumentRequest
     */
    updates: Array<StorageJsonFragment>;
}


/**
 * @export
 */
export const StorageAppendArrSubDocumentRequestAccessTypeEnum = {
    Public: 'public',
    Private: 'private',
    Protected: 'protected'
} as const;
export type StorageAppendArrSubDocumentRequestAccessTypeEnum = typeof StorageAppendArrSubDocumentRequestAccessTypeEnum[keyof typeof StorageAppendArrSubDocumentRequestAccessTypeEnum];


/**
 * Check if a given object implements the StorageAppendArrSubDocumentRequest interface.
 */
export function instanceOfStorageAppendArrSubDocumentRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "accessType" in value;
    isInstance = isInstance && "jsonBlobKey" in value;
    isInstance = isInstance && "ownerId" in value;
    isInstance = isInstance && "updates" in value;

    return isInstance;
}

export function StorageAppendArrSubDocumentRequestFromJSON(json: any): StorageAppendArrSubDocumentRequest {
    return StorageAppendArrSubDocumentRequestFromJSONTyped(json, false);
}

export function StorageAppendArrSubDocumentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageAppendArrSubDocumentRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessType': json['access_type'],
        'jsonBlobKey': json['json_blob_key'],
        'ownerId': json['owner_id'],
        'updates': ((json['updates'] as Array<any>).map(StorageJsonFragmentFromJSON)),
    };
}

export function StorageAppendArrSubDocumentRequestToJSON(value?: StorageAppendArrSubDocumentRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'access_type': value.accessType,
        'json_blob_key': value.jsonBlobKey,
        'owner_id': value.ownerId,
        'updates': ((value.updates as Array<any>).map(StorageJsonFragmentToJSON)),
    };
}

