/* tslint:disable */
/* eslint-disable */
/**
 * test
 * Your custom SDK
 *
 * The version of the OpenAPI document: test: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StorageGetJsonBlobRequest } from './StorageGetJsonBlobRequest';
import {
    StorageGetJsonBlobRequestFromJSON,
    StorageGetJsonBlobRequestFromJSONTyped,
    StorageGetJsonBlobRequestToJSON,
} from './StorageGetJsonBlobRequest';
import type { StorageGetJsonBlobResponse } from './StorageGetJsonBlobResponse';
import {
    StorageGetJsonBlobResponseFromJSON,
    StorageGetJsonBlobResponseFromJSONTyped,
    StorageGetJsonBlobResponseToJSON,
} from './StorageGetJsonBlobResponse';

/**
 * 
 * @export
 * @interface StorageBatchGetJsonBlobsSingleResponse
 */
export interface StorageBatchGetJsonBlobsSingleResponse {
    /**
     * 
     * @type {string}
     * @memberof StorageBatchGetJsonBlobsSingleResponse
     */
    message?: string;
    /**
     * 
     * @type {StorageGetJsonBlobRequest}
     * @memberof StorageBatchGetJsonBlobsSingleResponse
     */
    request?: StorageGetJsonBlobRequest;
    /**
     * 
     * @type {StorageGetJsonBlobResponse}
     * @memberof StorageBatchGetJsonBlobsSingleResponse
     */
    response?: StorageGetJsonBlobResponse;
    /**
     * 
     * @type {boolean}
     * @memberof StorageBatchGetJsonBlobsSingleResponse
     */
    success?: boolean;
}

/**
 * Check if a given object implements the StorageBatchGetJsonBlobsSingleResponse interface.
 */
export function instanceOfStorageBatchGetJsonBlobsSingleResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StorageBatchGetJsonBlobsSingleResponseFromJSON(json: any): StorageBatchGetJsonBlobsSingleResponse {
    return StorageBatchGetJsonBlobsSingleResponseFromJSONTyped(json, false);
}

export function StorageBatchGetJsonBlobsSingleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageBatchGetJsonBlobsSingleResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
        'request': !exists(json, 'request') ? undefined : StorageGetJsonBlobRequestFromJSON(json['request']),
        'response': !exists(json, 'response') ? undefined : StorageGetJsonBlobResponseFromJSON(json['response']),
        'success': !exists(json, 'success') ? undefined : json['success'],
    };
}

export function StorageBatchGetJsonBlobsSingleResponseToJSON(value?: StorageBatchGetJsonBlobsSingleResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'request': StorageGetJsonBlobRequestToJSON(value.request),
        'response': StorageGetJsonBlobResponseToJSON(value.response),
        'success': value.success,
    };
}

