/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v6 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StorageUpsertSubDocumentRequest } from './StorageUpsertSubDocumentRequest';
import {
    StorageUpsertSubDocumentRequestFromJSON,
    StorageUpsertSubDocumentRequestFromJSONTyped,
    StorageUpsertSubDocumentRequestToJSON,
} from './StorageUpsertSubDocumentRequest';
import type { StorageUpsertSubDocumentResponse } from './StorageUpsertSubDocumentResponse';
import {
    StorageUpsertSubDocumentResponseFromJSON,
    StorageUpsertSubDocumentResponseFromJSONTyped,
    StorageUpsertSubDocumentResponseToJSON,
} from './StorageUpsertSubDocumentResponse';

/**
 * 
 * @export
 * @interface StorageBatchUpsertSubDocumentSingleResponse
 */
export interface StorageBatchUpsertSubDocumentSingleResponse {
    /**
     * 
     * @type {string}
     * @memberof StorageBatchUpsertSubDocumentSingleResponse
     */
    message?: string;
    /**
     * 
     * @type {StorageUpsertSubDocumentRequest}
     * @memberof StorageBatchUpsertSubDocumentSingleResponse
     */
    request?: StorageUpsertSubDocumentRequest;
    /**
     * 
     * @type {StorageUpsertSubDocumentResponse}
     * @memberof StorageBatchUpsertSubDocumentSingleResponse
     */
    response?: StorageUpsertSubDocumentResponse;
    /**
     * 
     * @type {boolean}
     * @memberof StorageBatchUpsertSubDocumentSingleResponse
     */
    success?: boolean;
}

/**
 * Check if a given object implements the StorageBatchUpsertSubDocumentSingleResponse interface.
 */
export function instanceOfStorageBatchUpsertSubDocumentSingleResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StorageBatchUpsertSubDocumentSingleResponseFromJSON(json: any): StorageBatchUpsertSubDocumentSingleResponse {
    return StorageBatchUpsertSubDocumentSingleResponseFromJSONTyped(json, false);
}

export function StorageBatchUpsertSubDocumentSingleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageBatchUpsertSubDocumentSingleResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
        'request': !exists(json, 'request') ? undefined : StorageUpsertSubDocumentRequestFromJSON(json['request']),
        'response': !exists(json, 'response') ? undefined : StorageUpsertSubDocumentResponseFromJSON(json['response']),
        'success': !exists(json, 'success') ? undefined : json['success'],
    };
}

export function StorageBatchUpsertSubDocumentSingleResponseToJSON(value?: StorageBatchUpsertSubDocumentSingleResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'request': StorageUpsertSubDocumentRequestToJSON(value.request),
        'response': StorageUpsertSubDocumentResponseToJSON(value.response),
        'success': value.success,
    };
}

