/* tslint:disable */
/* eslint-disable */
/**
 * test
 * Your custom SDK
 *
 * The version of the OpenAPI document: test: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StorageBatchSingleBlobResponse } from './StorageBatchSingleBlobResponse';
import {
    StorageBatchSingleBlobResponseFromJSON,
    StorageBatchSingleBlobResponseFromJSONTyped,
    StorageBatchSingleBlobResponseToJSON,
} from './StorageBatchSingleBlobResponse';

/**
 * 
 * @export
 * @interface StorageBatchInsertBlobResponse
 */
export interface StorageBatchInsertBlobResponse {
    /**
     * 
     * @type {Array<StorageBatchSingleBlobResponse>}
     * @memberof StorageBatchInsertBlobResponse
     */
    results?: Array<StorageBatchSingleBlobResponse>;
}

/**
 * Check if a given object implements the StorageBatchInsertBlobResponse interface.
 */
export function instanceOfStorageBatchInsertBlobResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StorageBatchInsertBlobResponseFromJSON(json: any): StorageBatchInsertBlobResponse {
    return StorageBatchInsertBlobResponseFromJSONTyped(json, false);
}

export function StorageBatchInsertBlobResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageBatchInsertBlobResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(StorageBatchSingleBlobResponseFromJSON)),
    };
}

export function StorageBatchInsertBlobResponseToJSON(value?: StorageBatchInsertBlobResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(StorageBatchSingleBlobResponseToJSON)),
    };
}

