/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v6 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StorageGetSubDocumentRequest
 */
export interface StorageGetSubDocumentRequest {
    /**
     * Access to the counter. (public/protected/private)
     * @type {string}
     * @memberof StorageGetSubDocumentRequest
     */
    accessType: StorageGetSubDocumentRequestAccessTypeEnum;
    /**
     * Blob key
     * @type {string}
     * @memberof StorageGetSubDocumentRequest
     */
    jsonBlobKey: string;
    /**
     * Counter owner's user ID
     * @type {string}
     * @memberof StorageGetSubDocumentRequest
     */
    ownerId: string;
    /**
     * Path to the sub-document
     * @type {string}
     * @memberof StorageGetSubDocumentRequest
     */
    path: string;
}


/**
 * @export
 */
export const StorageGetSubDocumentRequestAccessTypeEnum = {
    Public: 'public',
    Private: 'private',
    Protected: 'protected'
} as const;
export type StorageGetSubDocumentRequestAccessTypeEnum = typeof StorageGetSubDocumentRequestAccessTypeEnum[keyof typeof StorageGetSubDocumentRequestAccessTypeEnum];


/**
 * Check if a given object implements the StorageGetSubDocumentRequest interface.
 */
export function instanceOfStorageGetSubDocumentRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "accessType" in value;
    isInstance = isInstance && "jsonBlobKey" in value;
    isInstance = isInstance && "ownerId" in value;
    isInstance = isInstance && "path" in value;

    return isInstance;
}

export function StorageGetSubDocumentRequestFromJSON(json: any): StorageGetSubDocumentRequest {
    return StorageGetSubDocumentRequestFromJSONTyped(json, false);
}

export function StorageGetSubDocumentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageGetSubDocumentRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessType': json['access_type'],
        'jsonBlobKey': json['json_blob_key'],
        'ownerId': json['owner_id'],
        'path': json['path'],
    };
}

export function StorageGetSubDocumentRequestToJSON(value?: StorageGetSubDocumentRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'access_type': value.accessType,
        'json_blob_key': value.jsonBlobKey,
        'owner_id': value.ownerId,
        'path': value.path,
    };
}

