/* tslint:disable */
/* eslint-disable */
/**
 * test
 * Your custom SDK
 *
 * The version of the OpenAPI document: test: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StorageAppendArrSubDocumentRequest } from './StorageAppendArrSubDocumentRequest';
import {
    StorageAppendArrSubDocumentRequestFromJSON,
    StorageAppendArrSubDocumentRequestFromJSONTyped,
    StorageAppendArrSubDocumentRequestToJSON,
} from './StorageAppendArrSubDocumentRequest';
import type { StorageAppendArrSubDocumentResponse } from './StorageAppendArrSubDocumentResponse';
import {
    StorageAppendArrSubDocumentResponseFromJSON,
    StorageAppendArrSubDocumentResponseFromJSONTyped,
    StorageAppendArrSubDocumentResponseToJSON,
} from './StorageAppendArrSubDocumentResponse';

/**
 * 
 * @export
 * @interface StorageBatchAppendArrSubDocumentSingleResponse
 */
export interface StorageBatchAppendArrSubDocumentSingleResponse {
    /**
     * 
     * @type {string}
     * @memberof StorageBatchAppendArrSubDocumentSingleResponse
     */
    message?: string;
    /**
     * 
     * @type {StorageAppendArrSubDocumentRequest}
     * @memberof StorageBatchAppendArrSubDocumentSingleResponse
     */
    request?: StorageAppendArrSubDocumentRequest;
    /**
     * 
     * @type {StorageAppendArrSubDocumentResponse}
     * @memberof StorageBatchAppendArrSubDocumentSingleResponse
     */
    response?: StorageAppendArrSubDocumentResponse;
    /**
     * 
     * @type {boolean}
     * @memberof StorageBatchAppendArrSubDocumentSingleResponse
     */
    success?: boolean;
}

/**
 * Check if a given object implements the StorageBatchAppendArrSubDocumentSingleResponse interface.
 */
export function instanceOfStorageBatchAppendArrSubDocumentSingleResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StorageBatchAppendArrSubDocumentSingleResponseFromJSON(json: any): StorageBatchAppendArrSubDocumentSingleResponse {
    return StorageBatchAppendArrSubDocumentSingleResponseFromJSONTyped(json, false);
}

export function StorageBatchAppendArrSubDocumentSingleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageBatchAppendArrSubDocumentSingleResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
        'request': !exists(json, 'request') ? undefined : StorageAppendArrSubDocumentRequestFromJSON(json['request']),
        'response': !exists(json, 'response') ? undefined : StorageAppendArrSubDocumentResponseFromJSON(json['response']),
        'success': !exists(json, 'success') ? undefined : json['success'],
    };
}

export function StorageBatchAppendArrSubDocumentSingleResponseToJSON(value?: StorageBatchAppendArrSubDocumentSingleResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'request': StorageAppendArrSubDocumentRequestToJSON(value.request),
        'response': StorageAppendArrSubDocumentResponseToJSON(value.response),
        'success': value.success,
    };
}

