/* tslint:disable */
/* eslint-disable */
/**
 * lap-legend-race-game
 * Your custom SDK
 *
 * The version of the OpenAPI document: lap-legend-race-game: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StorageGetSubDocumentResponse
 */
export interface StorageGetSubDocumentResponse {
    /**
     * Value of the sub-document
     * @type {object}
     * @memberof StorageGetSubDocumentResponse
     */
    value?: object;
}

/**
 * Check if a given object implements the StorageGetSubDocumentResponse interface.
 */
export function instanceOfStorageGetSubDocumentResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StorageGetSubDocumentResponseFromJSON(json: any): StorageGetSubDocumentResponse {
    return StorageGetSubDocumentResponseFromJSONTyped(json, false);
}

export function StorageGetSubDocumentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageGetSubDocumentResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function StorageGetSubDocumentResponseToJSON(value?: StorageGetSubDocumentResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
    };
}

