/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v6 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StorageGetAppendBlobRequest
 */
export interface StorageGetAppendBlobRequest {
    /**
     * Access to the append-blob. (public/protected/private)
     * @type {string}
     * @memberof StorageGetAppendBlobRequest
     */
    accessType: StorageGetAppendBlobRequestAccessTypeEnum;
    /**
     * Append-blob key
     * @type {string}
     * @memberof StorageGetAppendBlobRequest
     */
    appendBlobKey: string;
    /**
     * Append-blob owner's user ID
     * @type {string}
     * @memberof StorageGetAppendBlobRequest
     */
    ownerId: string;
}


/**
 * @export
 */
export const StorageGetAppendBlobRequestAccessTypeEnum = {
    Public: 'public',
    Private: 'private',
    Protected: 'protected'
} as const;
export type StorageGetAppendBlobRequestAccessTypeEnum = typeof StorageGetAppendBlobRequestAccessTypeEnum[keyof typeof StorageGetAppendBlobRequestAccessTypeEnum];


/**
 * Check if a given object implements the StorageGetAppendBlobRequest interface.
 */
export function instanceOfStorageGetAppendBlobRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "accessType" in value;
    isInstance = isInstance && "appendBlobKey" in value;
    isInstance = isInstance && "ownerId" in value;

    return isInstance;
}

export function StorageGetAppendBlobRequestFromJSON(json: any): StorageGetAppendBlobRequest {
    return StorageGetAppendBlobRequestFromJSONTyped(json, false);
}

export function StorageGetAppendBlobRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageGetAppendBlobRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessType': json['access_type'],
        'appendBlobKey': json['append_blob_key'],
        'ownerId': json['owner_id'],
    };
}

export function StorageGetAppendBlobRequestToJSON(value?: StorageGetAppendBlobRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'access_type': value.accessType,
        'append_blob_key': value.appendBlobKey,
        'owner_id': value.ownerId,
    };
}

