/* tslint:disable */
/* eslint-disable */
/**
 * test
 * Your custom SDK
 *
 * The version of the OpenAPI document: test: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StorageIncrementCounterResponse
 */
export interface StorageIncrementCounterResponse {
    /**
     * Value of the counter
     * @type {number}
     * @memberof StorageIncrementCounterResponse
     */
    count: number;
}

/**
 * Check if a given object implements the StorageIncrementCounterResponse interface.
 */
export function instanceOfStorageIncrementCounterResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "count" in value;

    return isInstance;
}

export function StorageIncrementCounterResponseFromJSON(json: any): StorageIncrementCounterResponse {
    return StorageIncrementCounterResponseFromJSONTyped(json, false);
}

export function StorageIncrementCounterResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageIncrementCounterResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': json['count'],
    };
}

export function StorageIncrementCounterResponseToJSON(value?: StorageIncrementCounterResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
    };
}

