/* tslint:disable */
/* eslint-disable */
/**
 * lap-legend-race-game
 * Your custom SDK
 *
 * The version of the OpenAPI document: lap-legend-race-game: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StorageAppendBlobAndOwner
 */
export interface StorageAppendBlobAndOwner {
    /**
     * 
     * @type {string}
     * @memberof StorageAppendBlobAndOwner
     */
    cas?: string;
    /**
     * 
     * @type {string}
     * @memberof StorageAppendBlobAndOwner
     */
    key?: string;
    /**
     * 
     * @type {string}
     * @memberof StorageAppendBlobAndOwner
     */
    ownerId?: string;
    /**
     * 
     * @type {string}
     * @memberof StorageAppendBlobAndOwner
     */
    value?: string;
}

/**
 * Check if a given object implements the StorageAppendBlobAndOwner interface.
 */
export function instanceOfStorageAppendBlobAndOwner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StorageAppendBlobAndOwnerFromJSON(json: any): StorageAppendBlobAndOwner {
    return StorageAppendBlobAndOwnerFromJSONTyped(json, false);
}

export function StorageAppendBlobAndOwnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageAppendBlobAndOwner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cas': !exists(json, 'cas') ? undefined : json['cas'],
        'key': !exists(json, 'key') ? undefined : json['key'],
        'ownerId': !exists(json, 'owner_id') ? undefined : json['owner_id'],
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function StorageAppendBlobAndOwnerToJSON(value?: StorageAppendBlobAndOwner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cas': value.cas,
        'key': value.key,
        'owner_id': value.ownerId,
        'value': value.value,
    };
}

