/* tslint:disable */
/* eslint-disable */
/**
 * lap-legend-race-game
 * Your custom SDK
 *
 * The version of the OpenAPI document: lap-legend-race-game: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StorageDeleteJsonBlobRequest } from './StorageDeleteJsonBlobRequest';
import {
    StorageDeleteJsonBlobRequestFromJSON,
    StorageDeleteJsonBlobRequestFromJSONTyped,
    StorageDeleteJsonBlobRequestToJSON,
} from './StorageDeleteJsonBlobRequest';

/**
 * 
 * @export
 * @interface StorageBatchDeleteJsonBlobsRequest
 */
export interface StorageBatchDeleteJsonBlobsRequest {
    /**
     * 
     * @type {Array<StorageDeleteJsonBlobRequest>}
     * @memberof StorageBatchDeleteJsonBlobsRequest
     */
    blobs?: Array<StorageDeleteJsonBlobRequest>;
}

/**
 * Check if a given object implements the StorageBatchDeleteJsonBlobsRequest interface.
 */
export function instanceOfStorageBatchDeleteJsonBlobsRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StorageBatchDeleteJsonBlobsRequestFromJSON(json: any): StorageBatchDeleteJsonBlobsRequest {
    return StorageBatchDeleteJsonBlobsRequestFromJSONTyped(json, false);
}

export function StorageBatchDeleteJsonBlobsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageBatchDeleteJsonBlobsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'blobs': !exists(json, 'blobs') ? undefined : ((json['blobs'] as Array<any>).map(StorageDeleteJsonBlobRequestFromJSON)),
    };
}

export function StorageBatchDeleteJsonBlobsRequestToJSON(value?: StorageBatchDeleteJsonBlobsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'blobs': value.blobs === undefined ? undefined : ((value.blobs as Array<any>).map(StorageDeleteJsonBlobRequestToJSON)),
    };
}

