/* tslint:disable */
/* eslint-disable */
/**
 * test
 * Your custom SDK
 *
 * The version of the OpenAPI document: test: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StorageGetJsonBlobResponse
 */
export interface StorageGetJsonBlobResponse {
    /**
     * CAS value used for future operations
     * @type {string}
     * @memberof StorageGetJsonBlobResponse
     */
    cas?: string;
    /**
     * Value of the blob
     * @type {object}
     * @memberof StorageGetJsonBlobResponse
     */
    value?: object;
}

/**
 * Check if a given object implements the StorageGetJsonBlobResponse interface.
 */
export function instanceOfStorageGetJsonBlobResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StorageGetJsonBlobResponseFromJSON(json: any): StorageGetJsonBlobResponse {
    return StorageGetJsonBlobResponseFromJSONTyped(json, false);
}

export function StorageGetJsonBlobResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageGetJsonBlobResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cas': !exists(json, 'cas') ? undefined : json['cas'],
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function StorageGetJsonBlobResponseToJSON(value?: StorageGetJsonBlobResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cas': value.cas,
        'value': value.value,
    };
}

