/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v6 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StorageBlobAndOwner } from './StorageBlobAndOwner';
import {
    StorageBlobAndOwnerFromJSON,
    StorageBlobAndOwnerFromJSONTyped,
    StorageBlobAndOwnerToJSON,
} from './StorageBlobAndOwner';
import type { StorageInsertBlobRequest } from './StorageInsertBlobRequest';
import {
    StorageInsertBlobRequestFromJSON,
    StorageInsertBlobRequestFromJSONTyped,
    StorageInsertBlobRequestToJSON,
} from './StorageInsertBlobRequest';

/**
 * 
 * @export
 * @interface StorageBatchSingleBlobResponse
 */
export interface StorageBatchSingleBlobResponse {
    /**
     * 
     * @type {string}
     * @memberof StorageBatchSingleBlobResponse
     */
    message?: string;
    /**
     * 
     * @type {StorageInsertBlobRequest}
     * @memberof StorageBatchSingleBlobResponse
     */
    request?: StorageInsertBlobRequest;
    /**
     * 
     * @type {StorageBlobAndOwner}
     * @memberof StorageBatchSingleBlobResponse
     */
    response?: StorageBlobAndOwner;
    /**
     * 
     * @type {boolean}
     * @memberof StorageBatchSingleBlobResponse
     */
    success?: boolean;
}

/**
 * Check if a given object implements the StorageBatchSingleBlobResponse interface.
 */
export function instanceOfStorageBatchSingleBlobResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StorageBatchSingleBlobResponseFromJSON(json: any): StorageBatchSingleBlobResponse {
    return StorageBatchSingleBlobResponseFromJSONTyped(json, false);
}

export function StorageBatchSingleBlobResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageBatchSingleBlobResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
        'request': !exists(json, 'request') ? undefined : StorageInsertBlobRequestFromJSON(json['request']),
        'response': !exists(json, 'response') ? undefined : StorageBlobAndOwnerFromJSON(json['response']),
        'success': !exists(json, 'success') ? undefined : json['success'],
    };
}

export function StorageBatchSingleBlobResponseToJSON(value?: StorageBatchSingleBlobResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'request': StorageInsertBlobRequestToJSON(value.request),
        'response': StorageBlobAndOwnerToJSON(value.response),
        'success': value.success,
    };
}

