/* tslint:disable */
/* eslint-disable */
/**
 * my-dev-cluster
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v6 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StorageReplaceBlobResponse
 */
export interface StorageReplaceBlobResponse {
    /**
     * CAS value used for future operations
     * @type {string}
     * @memberof StorageReplaceBlobResponse
     */
    cas?: string;
}

/**
 * Check if a given object implements the StorageReplaceBlobResponse interface.
 */
export function instanceOfStorageReplaceBlobResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StorageReplaceBlobResponseFromJSON(json: any): StorageReplaceBlobResponse {
    return StorageReplaceBlobResponseFromJSONTyped(json, false);
}

export function StorageReplaceBlobResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageReplaceBlobResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cas': !exists(json, 'cas') ? undefined : json['cas'],
    };
}

export function StorageReplaceBlobResponseToJSON(value?: StorageReplaceBlobResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cas': value.cas,
    };
}

