/* tslint:disable */
/* eslint-disable */
/**
 * lap-legend-race-game
 * Your custom SDK
 *
 * The version of the OpenAPI document: lap-legend-race-game: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SuspendUserRequest
 */
export interface SuspendUserRequest {
    /**
     * Duration in seconds for which the user should be suspended
     * @type {number}
     * @memberof SuspendUserRequest
     */
    suspendFor: number;
}

/**
 * Check if a given object implements the SuspendUserRequest interface.
 */
export function instanceOfSuspendUserRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "suspendFor" in value;

    return isInstance;
}

export function SuspendUserRequestFromJSON(json: any): SuspendUserRequest {
    return SuspendUserRequestFromJSONTyped(json, false);
}

export function SuspendUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuspendUserRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'suspendFor': json['suspend_for'],
    };
}

export function SuspendUserRequestToJSON(value?: SuspendUserRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'suspend_for': value.suspendFor,
    };
}

