/* tslint:disable */
/* eslint-disable */
/**
 * test
 * Your custom SDK
 *
 * The version of the OpenAPI document: test: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateAppendBlobRequest
 */
export interface UpdateAppendBlobRequest {
    /**
     * Value to be appended
     * @type {string}
     * @memberof UpdateAppendBlobRequest
     */
    value: string;
}

/**
 * Check if a given object implements the UpdateAppendBlobRequest interface.
 */
export function instanceOfUpdateAppendBlobRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function UpdateAppendBlobRequestFromJSON(json: any): UpdateAppendBlobRequest {
    return UpdateAppendBlobRequestFromJSONTyped(json, false);
}

export function UpdateAppendBlobRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAppendBlobRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': json['value'],
    };
}

export function UpdateAppendBlobRequestToJSON(value?: UpdateAppendBlobRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
    };
}

