/* tslint:disable */
/* eslint-disable */
/**
 * test
 * Your custom SDK
 *
 * The version of the OpenAPI document: test: v1 SDK
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StorageJsonFragment } from './StorageJsonFragment';
import {
    StorageJsonFragmentFromJSON,
    StorageJsonFragmentFromJSONTyped,
    StorageJsonFragmentToJSON,
} from './StorageJsonFragment';

/**
 * 
 * @export
 * @interface UpsertSubDocumentRequest
 */
export interface UpsertSubDocumentRequest {
    /**
     * Fragments to be upserted
     * @type {Array<StorageJsonFragment>}
     * @memberof UpsertSubDocumentRequest
     */
    updates: Array<StorageJsonFragment>;
}

/**
 * Check if a given object implements the UpsertSubDocumentRequest interface.
 */
export function instanceOfUpsertSubDocumentRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "updates" in value;

    return isInstance;
}

export function UpsertSubDocumentRequestFromJSON(json: any): UpsertSubDocumentRequest {
    return UpsertSubDocumentRequestFromJSONTyped(json, false);
}

export function UpsertSubDocumentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpsertSubDocumentRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'updates': ((json['updates'] as Array<any>).map(StorageJsonFragmentFromJSON)),
    };
}

export function UpsertSubDocumentRequestToJSON(value?: UpsertSubDocumentRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'updates': ((value.updates as Array<any>).map(StorageJsonFragmentToJSON)),
    };
}

